# ============================================================================
# Google Cloud Build Pipeline for erlmcp Marketplace
# Automates building, testing, and deploying erlmcp for GCP Marketplace
# ============================================================================

# This Cloud Build pipeline:
# 1. Builds the container image
# 2. Runs security vulnerability scanning
# 3. Pushes to Artifact Registry
# 4. Validates Terraform configurations
# 5. Runs integration tests
# 6. Creates deployment package

# Trigger configuration:
# - Push to main branch
# - Create tag (e.g., v3.0.0)
# - Manual trigger via Cloud Console

# Required substitutions:
# - _PROJECT_ID: GCP project ID
# - _REGION: GCP region (default: us-central1)
# - _IMAGE_NAME: Image name (default: erlmcp/erlmcp)
# - _IMAGE_TAG: Image tag (default: $SHORT_SHA)

# Optional substitutions:
# - _SKIP_TESTS: Skip integration tests (default: false)
# - _SCAN_MODE: Security scan mode (default: strict)

# ============================================================================
# Pipeline Steps
# ============================================================================

steps:
  # -------------------------------------------------------------------------
  # Step 1: Set up environment
  # -------------------------------------------------------------------------
  - id: 'setup'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build triggered by: $BUILD_ID"
        echo "Source: $REPO_NAME:$BRANCH_NAME"
        echo "Commit: $SHORT_SHA"
        echo "Image: $_IMAGE_NAME:$_IMAGE_TAG"

  # -------------------------------------------------------------------------
  # Step 2: Build container image
  # -------------------------------------------------------------------------
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:$_IMAGE_TAG'
      - '-t'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:latest'
      - '--build-arg'
      - 'BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
      - '--build-arg'
      - 'VCS_REF=$SHORT_SHA'
      - '--build-arg'
      - 'VERSION=$_IMAGE_TAG'
      - '.'
    timeout: '1200s'

  # -------------------------------------------------------------------------
  # Step 3: Run Trivy vulnerability scanner
  # -------------------------------------------------------------------------
  - id: 'trivy-scan'
    name: 'aquasec/trivy:latest'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        trivy image --severity HIGH,CRITICAL \
          --exit-code 1 \
          --format json \
          --output trivy-report.json \
          $_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:$_IMAGE_TAG || \
        if [ "$_SCAN_MODE" = "relaxed" ]; then
          echo "Scan found vulnerabilities but continuing in relaxed mode"
          exit 0
        else
          echo "Scan found vulnerabilities. Fix or use relaxed mode."
          cat trivy-report.json
          exit 1
        fi
    timeout: '300s'

  # -------------------------------------------------------------------------
  # Step 4: Run GCP Container Analysis
  # -------------------------------------------------------------------------
  - id: 'container-scan'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'artifacts'
      - 'docker'
      - 'images'
      - 'scan'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:$_IMAGE_TAG'
      - '--location'
      - '$_REGION'
      - '--format'
      - 'json'
      - '--timeout'
      - '300s'
    timeout: '600s'

  # -------------------------------------------------------------------------
  # Step 5: Push image to Artifact Registry
  # -------------------------------------------------------------------------
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:$_IMAGE_TAG'
    timeout: '600s'

  # -------------------------------------------------------------------------
  # Step 6: Validate Terraform configurations
  # -------------------------------------------------------------------------
  - id: 'terraform-validate'
    name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Validating Terraform configurations..."

        # Validate all modules
        for dir in marketplace/gcp/terraform/modules/*/; do
          echo "Validating $dir"
          cd "$dir"
          terraform init -backend=false -input=false
          terraform fmt -check
          terraform validate
        done

        # Validate examples
        for dir in marketplace/gcp/terraform/examples/*/; do
          echo "Validating $dir"
          cd "$dir"
          terraform init -backend=false -input=false
          terraform fmt -check
          terraform validate
        done
    timeout: '300s'

  # -------------------------------------------------------------------------
  # Step 7: Create deployment package
  # -------------------------------------------------------------------------
  - id: 'package'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating deployment package..."

        # Create package directory
        mkdir -p /workspace/deployment-package

        # Copy Marketplace schema files
        cp -r marketplace/gcp/marketplace-schema/* /workspace/deployment-package/

        # Copy Terraform modules
        cp -r marketplace/gcp/terraform /workspace/deployment-package/

        # Copy Helm chart
        cp -r marketplace/gcp/helm /workspace/deployment-package/

        # Copy scripts
        cp -r marketplace/gcp/scripts /workspace/deployment-package/

        # Create version file
        echo $_IMAGE_TAG > /workspace/deployment-package/VERSION

        # Create SHA256SUMS
        cd /workspace/deployment-package
        find . -type f -exec sha256sum {} \; > SHA256SUMS

        echo "Package created with $(find /workspace/deployment-package -type f | wc -l) files"
    timeout: '60s'

  # -------------------------------------------------------------------------
  # Step 8: Upload to GCS (optional, for distribution)
  # -------------------------------------------------------------------------
  - id: 'upload-package'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/deployment-package/*'
      - 'gs://$_PROJECT_ID-marketplace-packages/$_IMAGE_TAG/'
    timeout: '120s'

  # -------------------------------------------------------------------------
  # Step 9: Run integration tests (optional)
  # -------------------------------------------------------------------------
  - id: 'integration-test'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - 'marketplace/gcp/scripts/test-deployment.sh'
      - '--project'
      - '$_PROJECT_ID'
      - '--region'
      - '$_REGION'
      - '--gke-only'
    timeout: '1800s'
    waitFor:
      - 'push'

# ============================================================================
# Build Artifacts
# ============================================================================

artifacts:
  images:
    - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:$_IMAGE_TAG'
    - '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_IMAGE_NAME:latest'
  objects:
    location: 'gs://$_PROJECT_ID-build-logs/$BUILD_ID/'
    paths:
      - 'trivy-report.json'
      - '/workspace/deployment-package/**'

# ============================================================================
# Logs
# ============================================================================

logsBucket: 'gs://$_PROJECT_ID-cloudbuild-logs'

# ============================================================================
# Options
# ============================================================================

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true

# ============================================================================
# Substitutions (defaults)
# ============================================================================

substitutions:
  _PROJECT_ID: '${PROJECT_ID}'
  _REGION: 'us-central1'
  _IMAGE_NAME: 'erlmcp/erlmcp'
  _IMAGE_TAG: '${SHORT_SHA}'
  _SKIP_TESTS: 'false'
  _SCAN_MODE: 'strict'

# ============================================================================
# Timeout
# ============================================================================

timeout: '3600s'
