apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: erlmcp
  namespace: erlmcp
  labels:
    app.kubernetes.io/name: erlmcp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erlmcp
