apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: erlmcp
  namespace: erlmcp
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: erlmcp
  namespace: erlmcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: erlmcp
subjects:
  - kind: ServiceAccount
    name: erlmcp
    namespace: erlmcp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: erlmcp-metrics
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: erlmcp-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: erlmcp-metrics
subjects:
  - kind: ServiceAccount
    name: erlmcp
    namespace: erlmcp
