apiVersion: v1
kind: Secret
metadata:
  name: erlmcp-secrets
  namespace: erlmcp
type: Opaque
stringData:
  # Change these values in production using external secrets operator
  erlang-cookie: "erlmcp-change-me-in-production"
  jwt-secret: "change-me-in-production"
  db-password: "change-me-in-production"
  api-key: "change-me-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: erlmcp-tls
  namespace: erlmcp
type: kubernetes.io/tls
data:
  # Placeholder certificates - replace with actual certs
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: erlmcp
spec:
  provider:
    vault:
      server: "https://vault.erlmcp.io"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "erlmcp"
