apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erlmcp
  namespace: erlmcp
  labels:
    app.kubernetes.io/name: erlmcp
    app.kubernetes.io/component: mcp-server
spec:
  serviceName: erlmcp-headless
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: erlmcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erlmcp
        app.kubernetes.io/component: mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: erlmcp
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: init-wait
          image: busybox:1.36
          command: ["sh", "-c", "sleep 10"]
      containers:
        - name: erlmcp
          image: ghcr.io/seanchatmangpt/erlmcp:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: tcp
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: ws
              containerPort: 8082
              protocol: TCP
            - name: sse
              containerPort: 8083
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
            - name: distribution
              containerPort: 9100
              protocol: TCP
          env:
            - name: ERLMCP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: erlmcp-config
                  key: ERLMCP_LOG_LEVEL
            - name: ERLMCP_COOKIE
              valueFrom:
                secretKeyRef:
                  name: erlmcp-secrets
                  key: erlang-cookie
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ERLANG_NAME
              value: "erlmcp@$(POD_NAME).erlmcp-headless.$(NAMESPACE).svc.cluster.local"
            - name: ERL_MAX_PORTS
              value: "65536"
            - name: ERL_MAX_ETS_TABLES
              value: "20000"
          envFrom:
            - configMapRef:
                name: erlmcp-config
            - secretRef:
                name: erlmcp-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/erlmcp
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /var/log/erlmcp
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 10Gi
