-module(erlmcp_dev_portal_analytics).

-behaviour(cowboy_handler).

%% API exports
-export([init/2, handle/2, terminate/3]).

%%====================================================================
%% API Functions
%%====================================================================

init(Req, _Opts) ->
    %% Initialize analytics state
    State = #{},
    {ok, Req, State}.

handle(Req, State) ->
    %% Handle analytics requests
    Method = cowboy_req:method(Req),
    Path = cowboy_req:path(Req),

    case Method of
        <<"GET">> ->
            handle_get_analytics(Path, Req, State);
        _ ->
            cowboy_req:reply(405, #{}, <<"Method not allowed">>, Req)
    end.

terminate(_Reason, _Req, _State) ->
    ok.

%%====================================================================
%% Internal Functions
%%====================================================================

handle_get_analytics(<<"/analytics">>, Req, State) ->
    %% Return analytics dashboard
    {ok, Body} = render_analytics_dashboard(),
    cowboy_req:reply(200, #{<<"content-type">> => <<"text/html">>}, Body, Req);

handle_get_analytics(Path, Req, State) ->
    cowboy_req:reply(404, #{}, <<"Not found">>, Req).

render_analytics_dashboard() ->
    %% Render analytics dashboard HTML
    Html = <<
        "<!DOCTYPE html>"
        "<html>"
        "<head><title>Analytics - erlmcp</title>"
        "<script src='https://cdn.jsdelivr.net/npm/chart.js'></script>"
        "</head>"
        "<body>"
        "<h1>Analytics Dashboard</h1>"
        "<div class='analytics-grid'>"
        "<div class='chart-container'>"
        "<h2>API Usage</h2>"
        "<canvas id='usage-chart'></canvas>"
        "</div>"
        "<div class='chart-container'>"
        "<h2>Response Times</h2>"
        "<canvas id='response-times-chart'></canvas>"
        "</div>"
        "<div class='chart-container'>"
        "<h2>Error Rates</h2>"
        "<canvas id='error-rates-chart'></canvas>"
        "</div>"
        "<div class='chart-container'>"
        "<h2>Top APIs</h2>"
        "<canvas id='top-apis-chart'></canvas>"
        "</div>"
        "</div>"
        "<div class='analytics-summary'>"
        "<h2>Summary</h2>"
        "<div class='summary-cards'>"
        "<div class='summary-card'>"
        "<h3>Total Requests</h3>"
        "<div id='total-requests'>0</div>"
        "</div>"
        "<div class='summary-card'>"
        "<h3>Avg Response Time</h3>"
        "<div id='avg-response-time'>0ms</div>"
        "</div>"
        "<div class='summary-card'>"
        "<h3>Error Rate</h3>"
        "<div id='error-rate'>0%</div>"
        "</div>"
        "<div class='summary-card'>"
        "<h3>Active Users</h3>"
        "<div id='active-users'>0</div>"
        "</div>"
        "</div>"
        "</div>"
        "<div class='analytics-details'>"
        "<h2>Detailed Analytics</h2>"
        "<div class='details-tabs'>"
        "<button class='tab-btn active' data-tab='overview'>Overview</button>"
        "<button class='tab-btn' data-tab='apis'>APIs</button>"
        "<button class='tab-btn' data-tab='users'>Users</button>"
        "<button class='tab-btn' data-tab='errors'>Errors</button>"
        "</div>"
        "<div class='tab-content'>"
        "<div id='overview' class='tab-pane active'>"
        "<h3>Overview</h3>"
        "<div id='overview-content'></div>"
        "</div>"
        "<div id='apis' class='tab-pane'>"
        "<h3>API Performance</h3>"
        "<div id='apis-content'></div>"
        "</div>"
        "<div id='users' class='tab-pane'>"
        "<h3>User Activity</h3>"
        "<div id='users-content'></div>"
        "</div>"
        "<div id='errors' class='tab-pane'>"
        "<h3>Error Analysis</h3>"
        "<div id='errors-content'></div>"
        "</div>"
        "</div>"
        "</div>"
        "<script>"
        "// Initialize charts"
        "document.addEventListener('DOMContentLoaded', function() {"
        "  fetchAnalyticsData();"
        "  setupTabs();"
        "});"
        ""
        "function fetchAnalyticsData() {"
        "  fetch('/analytics/data')"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      updateSummary(data.summary);"
        "      renderCharts(data);"
        "    });"
        "}"
        ""
        "function updateSummary(summary) {"
        "  document.getElementById('total-requests').textContent = summary.total_requests;"
        "  document.getElementById('avg-response-time').textContent = summary.avg_response_time + 'ms';"
        "  document.getElementById('error-rate').textContent = summary.error_rate + '%';"
        "  document.getElementById('active-users').textContent = summary.active_users;"
        "}"
        ""
        "function renderCharts(data) {"
        "  // Usage Chart"
        "  new Chart(document.getElementById('usage-chart'), {"
        "    type: 'line',"
        "    data: {"
        "      labels: data.usage.labels,"
        "      datasets: [{"
        "        label: 'API Requests',"
        "        data: data.usage.values,"
        "        borderColor: 'rgb(75, 192, 192)',"
        "        tension: 0.1"
        "      }]"
        "    },"
        "    options: { responsive: true }"
        "  });"
        ""
        "  // Response Times Chart"
        "  new Chart(document.getElementById('response-times-chart'), {"
        "    type: 'bar',"
        "    data: {"
        "      labels: data.response_times.labels,"
        "      datasets: [{"
        "        label: 'Response Time (ms)',"
        "        data: data.response_times.values,"
        "        backgroundColor: 'rgba(54, 162, 235, 0.5)'"
        "      }]"
        "    },"
        "    options: { responsive: true }"
        "  });"
        ""
        "  // Error Rates Chart"
        "  new Chart(document.getElementById('error-rates-chart'), {"
        "    type: 'pie',"
        "    data: {"
        "      labels: data.error_rates.labels,"
        "      datasets: [{"
        "        data: data.error_rates.values,"
        "        backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56']"
        "      }]"
        "    },"
        "    options: { responsive: true }"
        "  });"
        ""
        "  // Top APIs Chart"
        "  new Chart(document.getElementById('top-apis-chart'), {"
        "    type: 'horizontalBar',"
        "    data: {"
        "      labels: data.top_apis.labels,"
        "      datasets: [{"
        "        label: 'Requests',"
        "        data: data.top_apis.values,"
        "        backgroundColor: 'rgba(153, 102, 255, 0.5)'"
        "      }]"
        "    },"
        "    options: { responsive: true }"
        "  });"
        "}"
        ""
        "function setupTabs() {"
        "  document.querySelectorAll('.tab-btn').forEach(btn => {"
        "    btn.addEventListener('click', function() {"
        "      const tabName = this.dataset.tab;"
        "      "
        "      // Update active tab"
        "      document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));"
        "      this.classList.add('active');"
        "      "
        "      // Update active pane"
        "      document.querySelectorAll('.tab-pane').forEach(p => p.classList.remove('active'));"
        "      document.getElementById(tabName).classList.add('active');"
        "      "
        "      // Load tab content"
        "      loadTabContent(tabName);"
        "    });"
        "  });"
        "}"
        ""
        "function loadTabContent(tabName) {"
        "  fetch(`/analytics/${tabName}`)"
        "    .then(response => response.json())"
        "    .then(data => {"
        "      const content = document.getElementById(`${tabName}-content`);"
        "      content.innerHTML = '';"
        "      "
        "      if (tabName === 'overview') {"
        "        content.innerHTML = renderOverview(data);"
        "      } else if (tabName === 'apis') {"
        "        content.innerHTML = renderAPIs(data);"
        "      } else if (tabName === 'users') {"
        "        content.innerHTML = renderUsers(data);"
        "      } else if (tabName === 'errors') {"
        "        content.innerHTML = renderErrors(data);"
        "      }"
        "    });"
        "}"
        ""
        "function renderOverview(data) {"
        "  let html = '<ul>';"
        "  data.forEach(item => {"
        "    html += `<li>${item.metric}: ${item.value}</li>`;"
        "  });"
        "  html += '</ul>';"
        "  return html;"
        "}"
        ""
        "function renderAPIs(data) {"
        "  let html = '<table>';"
        "  html += '<tr><th>API Name</th><th>Requests</th><th>Avg Response</th><th>Error Rate</th></tr>';"
        "  data.forEach(api => {"
        "    html += `<tr><td>${api.name}</td><td>${api.requests}</td><td>${api.avg_response}ms</td><td>${api.error_rate}%</td></tr>`;"
        "  });"
        "  html += '</table>';"
        "  return html;"
        "}"
        ""
        "function renderUsers(data) {"
        "  let html = '<ul>';"
        "  data.forEach(user => {"
        "    html += `<li>${user.name}: ${user.requests} requests</li>`;"
        "  });"
        "  html += '</ul>';"
        "  return html;"
        "}"
        ""
        "function renderErrors(data) {"
        "  let html = '<ul>';"
        "  data.forEach(error => {"
        "    html += `<li>${error.type}: ${error.count} occurrences</li>`;"
        "  });"
        "  html += '</ul>';"
        "  return html;"
        "}"
        "</script>"
        "</body>"
        "</html>"
    >>,
    {ok, Html}.