{application, erlmcp_api_gateway, [
    {description, "erlmcp v3 Enterprise API Gateway"},
    {vsn, "3.0.0"},
    {modules, [
        erlmcp_api_gateway_app,
        erlmcp_api_gateway_sup,
        erlmcp_api_gateway_routes,
        erlmcp_api_gateway_auth,
        erlmcp_api_gateway_oauth,
        erlmcp_api_gateway_rate_limiter,
        erlmcp_api_gateway_registry,
        erlmcp_api_gateway_monitor,
        erlmcp_api_gateway_cache,
        erlmcp_api_gateway_health,
        erlmcp_api_gateway_protocol,
        erlmcp_api_gateway_redis,
        erlmcp_api_gateway_redis_client,
        erlmcp_api_gateway_redis_pool,
        erlmcp_api_gateway_redis_worker,
        erlmcp_api_gateway_jwt,
        erlmcp_api_gateway_lifecycle,
        erlmcp_api_gateway_tester,
        erlmcp_api_gateway_analytics,
        erlmcp_api_gateway_compliance,
        erlmcp_api_gateway_openapi,
        erlmcp_api_dashboard,
        erlmcp_api_gateway_monetization
    ]},
    {applications, [
        kernel,
        stdlib,
        cowboy,
        jsx,
        uuid,
        crypto,
        redix,
        prometheus
    ]},
    {registered, []},
    {mod, {erlmcp_api_gateway_app, []}},
    {start_phases, []},
    {env, []}
]}.