#!/usr/bin/env bash
# ============================================================================
# emit_mermaid.sh - Generate Mermaid topology diagram from inside Docker
# ============================================================================
# CONSTITUTION: DOCKER-ONLY CONSTITUTION
#
# Generates a Mermaid diagram that proves:
#   1. Container runtime execution (is_docker check)
#   2. OTP version and node identity
#   3. Erlang distribution connectivity
#   4. MCP surface topology
#
# Output:
#   $OUT_DIR/topology.mmd - Mermaid diagram file
#
# Invariant: run => (receipt ^ mermaid)
#
# Usage:
#   RUN_ID=20260203T120000Z OUT_DIR=/work/receipts/... ./emit_mermaid.sh
# ============================================================================

set -euo pipefail

# ============================================================================
# HARD CHECK: Must be running inside Docker container
# ============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IS_DOCKER_SCRIPT="${SCRIPT_DIR}/../dev/is_docker.sh"

# Inline check if is_docker.sh doesn't exist
check_is_docker() {
    if [[ -f "/.dockerenv" ]]; then
        return 0
    fi
    if [[ -r "/proc/1/cgroup" ]] && grep -Eq "(docker|kubepods|containerd)" /proc/1/cgroup 2>/dev/null; then
        return 0
    fi
    return 1
}

if [[ -x "$IS_DOCKER_SCRIPT" ]]; then
    if ! "$IS_DOCKER_SCRIPT"; then
        echo "ANDON: FORBIDDEN_HOST_EXECUTION"
        echo "Refusal: emit_mermaid.sh MUST run inside Docker container"
        exit 2
    fi
else
    if ! check_is_docker; then
        echo "ANDON: FORBIDDEN_HOST_EXECUTION"
        echo "Refusal: emit_mermaid.sh MUST run inside Docker container"
        exit 2
    fi
fi

# ============================================================================
# Configuration
# ============================================================================
RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"
OUT_DIR="${OUT_DIR:-/workspace/receipts/$RUN_ID}"
WORKSPACE="${WORKSPACE:-/workspace}"

# Create output directory
mkdir -p "$OUT_DIR"

# ============================================================================
# Collect Runtime Facts
# ============================================================================
echo "Collecting container runtime facts..."

# Container identity
HOSTNAME="$(hostname 2>/dev/null || echo "unknown")"
CONTAINER_ID="$(cat /proc/self/cgroup 2>/dev/null | grep -oP 'docker/\K[a-f0-9]+' | head -1 || echo "unknown")"
if [[ "$CONTAINER_ID" == "unknown" ]] && [[ -f "/proc/1/cpuset" ]]; then
    CONTAINER_ID="$(cat /proc/1/cpuset 2>/dev/null | grep -oP '/docker/\K[a-f0-9]+' | head -1 || echo "unknown")"
fi
CONTAINER_SHORT="${CONTAINER_ID:0:12}"

# OTP Version
OTP_VSN="$(erl -noshell -eval 'io:format("~s",[erlang:system_info(otp_release)]), halt().' 2>/dev/null || echo "unknown")"

# ERTS Version
ERTS_VSN="$(erl -noshell -eval 'io:format("~s",[erlang:system_info(version)]), halt().' 2>/dev/null || echo "unknown")"

# Node name
NODE_NAME="$(erl -noshell -eval 'io:format("~p",[node()]), halt().' 2>/dev/null || echo "nonode@nohost")"

# Connected nodes (Erlang distribution)
CONNECTED_NODES="$(erl -noshell -eval 'io:format("~p",[nodes()]), halt().' 2>/dev/null || echo "[]")"

# Git SHA (if available)
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"

# Docker info (if socket mounted)
DOCKER_INFO="unavailable"
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    DOCKER_INFO="available"
fi

# Schedulers
SCHEDULERS="$(erl -noshell -eval 'io:format("~p",[erlang:system_info(schedulers_online)]), halt().' 2>/dev/null || echo "unknown")"

# Memory
MEMORY_MB="$(erl -noshell -eval 'io:format("~p",[erlang:memory(total) div 1048576]), halt().' 2>/dev/null || echo "unknown")"

# Timestamp
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ============================================================================
# Generate Mermaid Topology Diagram
# ============================================================================
echo "Generating Mermaid topology diagram..."

cat > "$OUT_DIR/topology.mmd" <<EOF
%%{init: {'theme': 'dark'}}%%
%% ============================================================================
%% ERLMCP RUNTIME TOPOLOGY PROOF
%% ============================================================================
%% AUTOGENERATED: $RUN_ID
%% TIMESTAMP: $TIMESTAMP
%% PROOF: container=$HOSTNAME id=$CONTAINER_SHORT otp=$OTP_VSN
%% GIT: $GIT_BRANCH@$GIT_SHA
%% ============================================================================

flowchart TB
    subgraph ContainerRuntime["Docker Container Runtime"]
        direction TB

        subgraph Container["Container: $HOSTNAME"]
            direction TB
            CID["Container ID: $CONTAINER_SHORT"]

            subgraph BEAM["BEAM VM"]
                direction TB
                OTP["OTP $OTP_VSN / ERTS $ERTS_VSN"]
                SCHED["Schedulers: $SCHEDULERS"]
                MEM["Memory: ${MEMORY_MB}MB"]
            end

            subgraph ErlNode["Erlang Node"]
                direction TB
                NODE["$NODE_NAME"]
            end
        end
    end

    subgraph Distribution["Erlang Distribution"]
        direction TB
        CONN["Connected Nodes:\\n$CONNECTED_NODES"]
    end

    subgraph MCPSurface["MCP Protocol Surface"]
        direction TB

        subgraph JSONRPCLayer["JSON-RPC 2.0 Layer"]
            ROUTER["Request Router"]
            CODEC["erlmcp_json_rpc"]
        end

        subgraph SessionLayer["Session Management"]
            SUPERVISOR["Session Supervisor\\n(simple_one_for_one)"]
            REGISTRY["gproc Registry"]
        end

        subgraph TransportLayer["Transport Layer"]
            STDIO["stdio"]
            TCP["tcp"]
            HTTP["http"]
            WS["websocket"]
            SSE["sse"]
        end

        subgraph MCPFeatures["MCP Features"]
            TOOLS["Tools"]
            RESOURCES["Resources"]
            PROMPTS["Prompts"]
            SUBS["Subscriptions"]
            PROGRESS["Progress"]
        end
    end

    subgraph ObservabilityLayer["Observability"]
        direction TB
        LOGGER["logger"]
        METRICS["prometheus_metrics"]
        OTEL["opentelemetry"]
    end

    %% Connections
    Container --> BEAM
    BEAM --> ErlNode
    ErlNode --> Distribution
    ErlNode --> MCPSurface

    ROUTER --> SUPERVISOR
    SUPERVISOR --> REGISTRY
    ROUTER --> CODEC

    SUPERVISOR --> TransportLayer
    SUPERVISOR --> MCPFeatures

    Container --> ObservabilityLayer

    %% Receipt Note
    subgraph ReceiptProof["Receipt Proof"]
        direction TB
        RECEIPT["run_id: $RUN_ID\\ngit_sha: $GIT_SHA\\nimage: see meta.txt\\ngate_logs: see *.log"]
    end

    Container --- ReceiptProof

    %% Styling
    classDef container fill:#1a1a2e,stroke:#16213e,color:#e94560
    classDef beam fill:#0f3460,stroke:#16213e,color:#e94560
    classDef mcp fill:#533483,stroke:#16213e,color:#00fff5
    classDef obs fill:#2d4a22,stroke:#16213e,color:#00ff00
    classDef note fill:#222,stroke:#555,color:#fff

    class Container,ContainerRuntime container
    class BEAM,ErlNode,OTP,SCHED,MEM beam
    class MCPSurface,JSONRPCLayer,SessionLayer,TransportLayer,MCPFeatures mcp
    class ObservabilityLayer,LOGGER,METRICS,OTEL obs
    class ReceiptProof,RECEIPT note
EOF

echo "OK: Generated $OUT_DIR/topology.mmd"

# ============================================================================
# Generate Meta File
# ============================================================================
cat > "$OUT_DIR/topology_meta.json" <<EOF
{
  "run_id": "$RUN_ID",
  "timestamp": "$TIMESTAMP",
  "container": {
    "hostname": "$HOSTNAME",
    "id": "$CONTAINER_ID",
    "short_id": "$CONTAINER_SHORT"
  },
  "erlang": {
    "otp_release": "$OTP_VSN",
    "erts_version": "$ERTS_VSN",
    "node": "$NODE_NAME",
    "connected_nodes": "$CONNECTED_NODES",
    "schedulers": "$SCHEDULERS",
    "memory_mb": "$MEMORY_MB"
  },
  "git": {
    "sha": "$GIT_SHA",
    "branch": "$GIT_BRANCH"
  },
  "docker": {
    "socket_available": "$DOCKER_INFO"
  },
  "is_docker": true
}
EOF

echo "OK: Generated $OUT_DIR/topology_meta.json"

# ============================================================================
# Output summary
# ============================================================================
echo ""
echo "=========================================="
echo "TOPOLOGY PROOF GENERATED"
echo "=========================================="
echo "RUN_ID:     $RUN_ID"
echo "CONTAINER:  $HOSTNAME ($CONTAINER_SHORT)"
echo "OTP:        $OTP_VSN"
echo "NODE:       $NODE_NAME"
echo "CONNECTED:  $CONNECTED_NODES"
echo "GIT:        $GIT_BRANCH@$GIT_SHA"
echo ""
echo "FILES:"
echo "  $OUT_DIR/topology.mmd"
echo "  $OUT_DIR/topology_meta.json"
echo "=========================================="
