#!/usr/bin/env bash
# ============================================================================
# emit_swarm_k8s_mermaid.sh - Docker Swarm / Kubernetes Topology Diagram
# ============================================================================
# CONSTITUTION: DOCKER-ONLY CONSTITUTION
#
# Generates a Mermaid diagram showing infrastructure topology:
#   - Docker Swarm: services, replicas, overlay networks
#   - Kubernetes: pods, services, deployments, namespaces
#   - Docker Compose: services, networks, volumes
#
# This is the INFRASTRUCTURE view (what platform orchestrates)
# vs emit_cluster_mermaid.sh which shows BEAM cluster (what Erlang sees)
#
# Usage:
#   ./emit_swarm_k8s_mermaid.sh
#   MODE=swarm ./emit_swarm_k8s_mermaid.sh
#   MODE=k8s NAMESPACE=erlmcp ./emit_swarm_k8s_mermaid.sh
#   MODE=compose ./emit_swarm_k8s_mermaid.sh
#
# Output:
#   $OUT_DIR/infrastructure_topology.mmd - Mermaid diagram
#   $OUT_DIR/infrastructure_meta.json    - JSON metadata
# ============================================================================

set -euo pipefail

# ============================================================================
# HARD CHECK: Must be running inside Docker container
# ============================================================================
check_is_docker() {
    if [[ -f "/.dockerenv" ]]; then
        return 0
    fi
    if [[ -r "/proc/1/cgroup" ]] && grep -Eq "(docker|kubepods|containerd)" /proc/1/cgroup 2>/dev/null; then
        return 0
    fi
    return 1
}

if ! check_is_docker; then
    echo "ANDON: FORBIDDEN_HOST_EXECUTION"
    echo "Refusal: emit_swarm_k8s_mermaid.sh MUST run inside Docker container"
    exit 2
fi

# ============================================================================
# Configuration
# ============================================================================
RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"
OUT_DIR="${OUT_DIR:-/workspace/receipts/$RUN_ID}"
MODE="${MODE:-auto}"  # auto, swarm, k8s, compose
NAMESPACE="${NAMESPACE:-default}"

mkdir -p "$OUT_DIR"

TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
HOSTNAME=$(hostname)

# ============================================================================
# Auto-detect Mode
# ============================================================================
detect_mode() {
    if [[ "$MODE" != "auto" ]]; then
        echo "$MODE"
        return
    fi

    # Check for Kubernetes
    if command -v kubectl >/dev/null 2>&1 && kubectl cluster-info >/dev/null 2>&1; then
        echo "k8s"
        return
    fi

    # Check for Docker Swarm
    if command -v docker >/dev/null 2>&1 && docker info 2>/dev/null | grep -q "Swarm: active"; then
        echo "swarm"
        return
    fi

    # Check for Docker (compose mode)
    if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
        echo "compose"
        return
    fi

    # Default to compose (most common development setup)
    echo "compose"
}

DETECTED_MODE=$(detect_mode)
echo "Detected infrastructure mode: $DETECTED_MODE"

# ============================================================================
# Docker Swarm Mode
# ============================================================================
generate_swarm_diagram() {
    echo "Generating Docker Swarm topology..."

    local services_output networks_output nodes_output
    services_output=$(docker service ls --format '{{.Name}}\t{{.Replicas}}\t{{.Image}}' 2>/dev/null || echo "")
    networks_output=$(docker network ls --filter "driver=overlay" --format '{{.Name}}\t{{.Driver}}' 2>/dev/null || echo "")
    nodes_output=$(docker node ls --format '{{.Hostname}}\t{{.Status}}\t{{.Availability}}' 2>/dev/null || echo "")

    cat > "$OUT_DIR/infrastructure_topology.mmd" <<EOF
%%{init: {'theme': 'dark'}}%%
%% ============================================================================
%% DOCKER SWARM INFRASTRUCTURE TOPOLOGY
%% ============================================================================
%% AUTOGENERATED: $RUN_ID
%% TIMESTAMP: $TIMESTAMP
%% MODE: swarm
%% ============================================================================

flowchart TB
    subgraph SwarmCluster["Docker Swarm Cluster"]
        direction TB

        subgraph Managers["Manager Nodes"]
            direction TB
EOF

    # Add nodes
    if [[ -n "$nodes_output" ]]; then
        NODE_NUM=1
        while IFS=$'\t' read -r name status availability; do
            if [[ -n "$name" ]]; then
                echo "            NODE$NODE_NUM[\"$name\\nStatus: $status\\nAvail: $availability\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                NODE_NUM=$((NODE_NUM + 1))
            fi
        done <<< "$nodes_output"
    else
        echo "            NONODES[\"No nodes visible\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end

        subgraph Services["Swarm Services"]
            direction TB
EOF

    # Add services
    if [[ -n "$services_output" ]]; then
        SVC_NUM=1
        while IFS=$'\t' read -r name replicas image; do
            if [[ -n "$name" ]]; then
                echo "            SVC$SVC_NUM[\"$name\\nReplicas: $replicas\\nImage: $image\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                SVC_NUM=$((SVC_NUM + 1))
            fi
        done <<< "$services_output"
    else
        echo "            NOSERVICES[\"No services deployed\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end

        subgraph OverlayNetworks["Overlay Networks"]
            direction TB
EOF

    # Add networks
    if [[ -n "$networks_output" ]]; then
        NET_NUM=1
        while IFS=$'\t' read -r name driver; do
            if [[ -n "$name" ]]; then
                echo "            NET$NET_NUM[\"$name ($driver)\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                NET_NUM=$((NET_NUM + 1))
            fi
        done <<< "$networks_output"
    else
        echo "            NONETS[\"No overlay networks\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end
    end

    Managers --> Services
    Services --> OverlayNetworks

    classDef manager fill:#0f3460,stroke:#16213e,color:#00fff5
    classDef service fill:#533483,stroke:#16213e,color:#fff
    classDef network fill:#2d4a22,stroke:#16213e,color:#00ff00

    class Managers,NODE1,NODE2,NODE3 manager
    class Services,SVC1,SVC2,SVC3,SVC4 service
    class OverlayNetworks,NET1,NET2,NET3 network
EOF

    # Generate meta
    cat > "$OUT_DIR/infrastructure_meta.json" <<EOF
{
  "run_id": "$RUN_ID",
  "timestamp": "$TIMESTAMP",
  "mode": "swarm",
  "hostname": "$HOSTNAME",
  "swarm": {
    "services": "$services_output",
    "networks": "$networks_output",
    "nodes": "$nodes_output"
  },
  "is_docker": true
}
EOF
}

# ============================================================================
# Kubernetes Mode
# ============================================================================
generate_k8s_diagram() {
    echo "Generating Kubernetes topology..."

    local pods_output services_output deployments_output
    pods_output=$(kubectl get pods -n "$NAMESPACE" -o custom-columns='NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName' --no-headers 2>/dev/null || echo "")
    services_output=$(kubectl get services -n "$NAMESPACE" -o custom-columns='NAME:.metadata.name,TYPE:.spec.type,CLUSTER-IP:.spec.clusterIP' --no-headers 2>/dev/null || echo "")
    deployments_output=$(kubectl get deployments -n "$NAMESPACE" -o custom-columns='NAME:.metadata.name,READY:.status.readyReplicas,DESIRED:.spec.replicas' --no-headers 2>/dev/null || echo "")

    cat > "$OUT_DIR/infrastructure_topology.mmd" <<EOF
%%{init: {'theme': 'dark'}}%%
%% ============================================================================
%% KUBERNETES INFRASTRUCTURE TOPOLOGY
%% ============================================================================
%% AUTOGENERATED: $RUN_ID
%% TIMESTAMP: $TIMESTAMP
%% MODE: kubernetes
%% NAMESPACE: $NAMESPACE
%% ============================================================================

flowchart TB
    subgraph K8sCluster["Kubernetes Cluster"]
        direction TB

        subgraph Namespace["Namespace: $NAMESPACE"]
            direction TB

            subgraph Deployments["Deployments"]
                direction TB
EOF

    # Add deployments
    if [[ -n "$deployments_output" ]]; then
        DEP_NUM=1
        while read -r name ready desired; do
            if [[ -n "$name" ]]; then
                echo "                DEP$DEP_NUM[\"$name\\nReady: $ready/$desired\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                DEP_NUM=$((DEP_NUM + 1))
            fi
        done <<< "$deployments_output"
    else
        echo "                NODEPS[\"No deployments\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
            end

            subgraph Pods["Pods"]
                direction TB
EOF

    # Add pods
    if [[ -n "$pods_output" ]]; then
        POD_NUM=1
        while read -r name status node; do
            if [[ -n "$name" ]]; then
                echo "                POD$POD_NUM[\"$name\\nStatus: $status\\nNode: $node\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                POD_NUM=$((POD_NUM + 1))
            fi
        done <<< "$pods_output"
    else
        echo "                NOPODS[\"No pods\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
            end

            subgraph K8sServices["Services"]
                direction TB
EOF

    # Add services
    if [[ -n "$services_output" ]]; then
        SVC_NUM=1
        while read -r name type clusterip; do
            if [[ -n "$name" ]]; then
                echo "                KSVC$SVC_NUM[\"$name\\nType: $type\\nIP: $clusterip\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                SVC_NUM=$((SVC_NUM + 1))
            fi
        done <<< "$services_output"
    else
        echo "                NOSVCS[\"No services\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
            end
        end
    end

    Deployments --> Pods
    K8sServices --> Pods

    classDef deployment fill:#0f3460,stroke:#16213e,color:#00fff5
    classDef pod fill:#533483,stroke:#16213e,color:#fff
    classDef service fill:#2d4a22,stroke:#16213e,color:#00ff00

    class Deployments,DEP1,DEP2 deployment
    class Pods,POD1,POD2,POD3 pod
    class K8sServices,KSVC1,KSVC2 service
EOF

    # Generate meta
    cat > "$OUT_DIR/infrastructure_meta.json" <<EOF
{
  "run_id": "$RUN_ID",
  "timestamp": "$TIMESTAMP",
  "mode": "kubernetes",
  "namespace": "$NAMESPACE",
  "hostname": "$HOSTNAME",
  "kubernetes": {
    "deployments": $(echo "$deployments_output" | wc -l),
    "pods": $(echo "$pods_output" | wc -l),
    "services": $(echo "$services_output" | wc -l)
  },
  "is_docker": true
}
EOF
}

# ============================================================================
# Docker Compose Mode
# ============================================================================
generate_compose_diagram() {
    echo "Generating Docker Compose topology..."

    local containers_output networks_output volumes_output
    containers_output=$(docker ps --format '{{.Names}}\t{{.Status}}\t{{.Image}}\t{{.Ports}}' 2>/dev/null || echo "")
    networks_output=$(docker network ls --format '{{.Name}}\t{{.Driver}}' 2>/dev/null || echo "")
    volumes_output=$(docker volume ls --format '{{.Name}}\t{{.Driver}}' 2>/dev/null || echo "")

    cat > "$OUT_DIR/infrastructure_topology.mmd" <<EOF
%%{init: {'theme': 'dark'}}%%
%% ============================================================================
%% DOCKER COMPOSE INFRASTRUCTURE TOPOLOGY
%% ============================================================================
%% AUTOGENERATED: $RUN_ID
%% TIMESTAMP: $TIMESTAMP
%% MODE: compose
%% HOSTNAME: $HOSTNAME
%% ============================================================================

flowchart TB
    subgraph DockerHost["Docker Host: $HOSTNAME"]
        direction TB

        subgraph Containers["Running Containers"]
            direction TB
EOF

    # Add containers
    if [[ -n "$containers_output" ]]; then
        CTR_NUM=1
        while IFS=$'\t' read -r name status image ports; do
            if [[ -n "$name" ]]; then
                # Truncate long image names
                short_image=$(echo "$image" | cut -d'/' -f2- | cut -c1-30)
                echo "            CTR$CTR_NUM[\"$name\\n$status\\n$short_image\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                CTR_NUM=$((CTR_NUM + 1))
            fi
        done <<< "$containers_output"
    else
        echo "            NOCTR[\"No containers running\\n(docker socket unavailable)\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end

        subgraph Networks["Docker Networks"]
            direction TB
EOF

    # Add networks (limit to avoid clutter)
    if [[ -n "$networks_output" ]]; then
        NET_NUM=1
        while IFS=$'\t' read -r name driver; do
            if [[ -n "$name" && $NET_NUM -le 10 ]]; then
                echo "            NET$NET_NUM[\"$name ($driver)\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                NET_NUM=$((NET_NUM + 1))
            fi
        done <<< "$networks_output"
    else
        echo "            NONET[\"No networks visible\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end

        subgraph Volumes["Docker Volumes"]
            direction TB
EOF

    # Add volumes (limit to avoid clutter)
    if [[ -n "$volumes_output" ]]; then
        VOL_NUM=1
        while IFS=$'\t' read -r name driver; do
            if [[ -n "$name" && $VOL_NUM -le 10 ]]; then
                echo "            VOL$VOL_NUM[\"$name\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
                VOL_NUM=$((VOL_NUM + 1))
            fi
        done <<< "$volumes_output"
    else
        echo "            NOVOL[\"No volumes visible\"]" >> "$OUT_DIR/infrastructure_topology.mmd"
    fi

    cat >> "$OUT_DIR/infrastructure_topology.mmd" <<EOF
        end
    end

    subgraph CurrentContainer["This Container"]
        direction TB
        SELF["$HOSTNAME\\n(running receipt generation)"]
    end

    Containers --> Networks
    Containers --> Volumes
    DockerHost --> CurrentContainer

    classDef container fill:#533483,stroke:#16213e,color:#fff
    classDef network fill:#0f3460,stroke:#16213e,color:#00fff5
    classDef volume fill:#2d4a22,stroke:#16213e,color:#00ff00
    classDef self fill:#5a1a1a,stroke:#e94560,color:#fff

    class Containers,CTR1,CTR2,CTR3,CTR4,CTR5 container
    class Networks,NET1,NET2,NET3,NET4 network
    class Volumes,VOL1,VOL2,VOL3,VOL4 volume
    class CurrentContainer,SELF self
EOF

    # Count items
    local ctr_count net_count vol_count
    ctr_count=$(echo "$containers_output" | grep -c . || echo "0")
    net_count=$(echo "$networks_output" | grep -c . || echo "0")
    vol_count=$(echo "$volumes_output" | grep -c . || echo "0")

    # Generate meta
    cat > "$OUT_DIR/infrastructure_meta.json" <<EOF
{
  "run_id": "$RUN_ID",
  "timestamp": "$TIMESTAMP",
  "mode": "compose",
  "hostname": "$HOSTNAME",
  "docker": {
    "containers": $ctr_count,
    "networks": $net_count,
    "volumes": $vol_count,
    "socket_available": $(command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 && echo "true" || echo "false")
  },
  "is_docker": true
}
EOF
}

# ============================================================================
# Generate Based on Mode
# ============================================================================
case "$DETECTED_MODE" in
    swarm)
        generate_swarm_diagram
        ;;
    k8s|kubernetes)
        generate_k8s_diagram
        ;;
    compose|*)
        generate_compose_diagram
        ;;
esac

echo "OK: Generated $OUT_DIR/infrastructure_topology.mmd"
echo "OK: Generated $OUT_DIR/infrastructure_meta.json"

# ============================================================================
# Output Summary
# ============================================================================
echo ""
echo "=========================================="
echo "INFRASTRUCTURE TOPOLOGY GENERATED"
echo "=========================================="
echo "RUN_ID:    $RUN_ID"
echo "MODE:      $DETECTED_MODE"
echo "HOSTNAME:  $HOSTNAME"
echo ""
echo "FILES:"
echo "  $OUT_DIR/infrastructure_topology.mmd"
echo "  $OUT_DIR/infrastructure_meta.json"
echo "=========================================="
