apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: erlmcp
  namespace: argocd
  labels:
    app.kubernetes.io/name: erlmcp
spec:
  description: erlmcp - Erlang/OTP MCP SDK
  sourceRepos:
    - https://github.com/seanchatmangpt/erlmcp.git
  destinations:
    - namespace: erlmcp-dev
      server: https://kubernetes.default.svc
    - namespace: erlmcp-staging
      server: https://kubernetes.default.svc
    - namespace: erlmcp-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erlmcp-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: erlmcp
spec:
  project: erlmcp
  source:
    repoURL: https://github.com/seanchatmangpt/erlmcp.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    pruneLast: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
