# erlmcp v3 Configuration
# Auto-generated by Terraform

[general]
environment = <%= environment %>
log_level = <%= log_level %>
enable_metrics = <%= metrics_enabled %>
enable_tracing = <%= tracing_enabled %>

[server]
port = 8080
ssl_port = 8443
workers = <%= var.replicas %>
max_connections = <%= var.max_connections %>
timeout = 30000

[registry]
backend = <%= var.registry_backend %>
ttl = 3600
max_size = 1000000
cleanup_interval = 300

[session]
backend = <%= var.session_backend %>
ttl = 86400
max_sessions = <%= var.max_sessions %>
cleanup_interval = 600

[transport]
stdio_enabled = true
tcp_enabled = true
http_enabled = true
websocket_enabled = true
sse_enabled = true

[auth]
provider = <%= var.auth_provider %>
jwt_secret = <%= var.jwt_secret %>
oauth_enabled = <%= var.oauth_enabled %>
rate_limit = 1000

[metrics]
prometheus_enabled = true
port = 9090
path = /metrics

[tracing]
jaeger_enabled = true
jaeger_endpoint = <%= var.jaeger_endpoint %>
sample_rate = <%= var.tracing_sample_rate %>

[security]
enable_tls = true
tls_cert = /etc/tls/tls.crt
tls_key = /etc/tls/tls.key
enable_cors = true
cors_origins = <%= var.cors_origins %>

[database]
url = <%= var.database_url %>
pool_size = 10
timeout = 5000

[cache]
backend = <%= var.cache_backend %>
url = <%= var.redis_url %>
max_connections = 100
ttl = 3600

[logging]
level = <%= var.log_level %>
format = json
file = /var/log/erlmcp/app.log
rotate_size = 100MB
rotate_count = 5

[monitoring]
health_check_path = /health
health_check_interval = 30
metrics_path = /metrics
tracing_path = /tracing

[deployment]
canary_enabled = <%= var.enable_canary %>
blue_green_enabled = <%= var.enable_blue_green %>
health_check_grace_period = 30
rolling_update_timeout = 600

[performance]
max_concurrent_requests = <%= var.max_concurrent_requests %>
request_timeout = <%= var.request_timeout %>
connection_pool_size = <%= var.connection_pool_size %>

[features]
feature_flags = <%= json_encode(var.feature_flags) %>
enable_experimental = <%= var.enable_experimental %>