#!/usr/bin/env bash
# hex-mirror-alternatives.sh - Test multiple Hex.pm mirrors
# Purpose: Diagnose Hex package download issues by testing alternative mirrors
# Usage: ./hex-mirror-alternatives.sh [--package PACKAGE] [--version VERSION]

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/log/hex-mirror-test"
CACHE_DIR="${PROJECT_ROOT}/.hex-mirror-cache"
TIMEOUT=10

# Test package (default)
TEST_PACKAGE="${1:-jsx}"
TEST_VERSION="${2:-3.1.0}"

# Mirror list
declare -A MIRRORS=(
    ["hex.pm"]="https://hex.pm"
    ["aliyun"]="https://mirrors.aliyun.com/hex"
    ["fly-cdn"]="https://hexpm-cdn.fly.dev"
    ["erlang-pkg"]="https://hex-cdn.erlang-package.com"
)

# API endpoints
declare -A API_ENDPOINTS=(
    ["hex.pm"]="https://hex.pm/api"
    ["aliyun"]="https://mirrors.aliyun.com/hex/api"
    ["fly-cdn"]="https://hexpm-cdn.fly.dev/api"
    ["erlang-pkg"]="https://hex-cdn.erlang-package.com/api"
)

# Setup
mkdir -p "${LOG_DIR}" "${CACHE_DIR}"

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "${LOG_DIR}/test.log"
}

log_success() {
    echo -e "${GREEN}✓${NC} $*" | tee -a "${LOG_DIR}/test.log"
}

log_error() {
    echo -e "${RED}✗${NC} $*" | tee -a "${LOG_DIR}/test.log"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $*" | tee -a "${LOG_DIR}/test.log"
}

# Test connection speed and availability
test_mirror_connectivity() {
    local mirror_name="$1"
    local mirror_url="$2"
    
    log "Testing connectivity to ${mirror_name}: ${mirror_url}"
    
    # Test 1: Basic connectivity with HEAD request
    local start_time=$(date +%s%3N)
    if curl -s -I -m "${TIMEOUT}" "${mirror_url}" >/dev/null 2>&1; then
        local end_time=$(date +%s%3N)
        local duration=$((end_time - start_time))
        log_success "${mirror_name}: Connected (${duration}ms)"
        echo "${duration}"
        return 0
    else
        log_error "${mirror_name}: Connection failed"
        echo "-1"
        return 1
    fi
}

# Test API endpoint
test_api_endpoint() {
    local mirror_name="$1"
    local api_url="$2"
    
    log "Testing API endpoint: ${mirror_name}"
    
    # Test packages endpoint
    local response
    response=$(curl -s -m "${TIMEOUT}" "${api_url}/packages" 2>&1)
    
    if echo "${response}" | grep -q '"name"'; then
        log_success "${mirror_name}: API responding"
        return 0
    else
        log_error "${mirror_name}: API not responding correctly"
        return 1
    fi
}

# Test package download
test_package_download() {
    local mirror_name="$1"
    local repo_url="$2"
    local package="$3"
    local version="$4"
    
    log "Testing package download: ${package}-${version} from ${mirror_name}"
    
    # Construct download URL
    local download_url="${repo_url}/tarballs/${package}-${version}.tar"
    local output_file="${CACHE_DIR}/${mirror_name}-${package}-${version}.tar"
    
    # Download with timing
    local start_time=$(date +%s%3N)
    if curl -s -f -m 30 -o "${output_file}" "${download_url}" 2>&1; then
        local end_time=$(date +%s%3N)
        local duration=$((end_time - start_time))
        local size=$(stat -f%z "${output_file}" 2>/dev/null || stat -c%s "${output_file}" 2>/dev/null || echo "0")
        local size_kb=$((size / 1024))
        
        log_success "${mirror_name}: Downloaded ${package}-${version} (${size_kb}KB in ${duration}ms)"
        
        # Verify tarball
        if tar -tzf "${output_file}" >/dev/null 2>&1; then
            log_success "${mirror_name}: Tarball valid"
            echo "${duration},${size}"
            return 0
        else
            log_error "${mirror_name}: Tarball corrupted"
            rm -f "${output_file}"
            return 1
        fi
    else
        log_error "${mirror_name}: Download failed"
        return 1
    fi
}

# Generate rebar3 config for working mirrors
generate_rebar_config() {
    local -a working_mirrors=("$@")
    local config_file="${PROJECT_ROOT}/rebar.config.mirrors"
    
    log "Generating rebar3 config with working mirrors"
    
    cat > "${config_file}" << 'CONFIG_EOF'
%% Generated by hex-mirror-alternatives.sh
%% Hex.pm mirror configuration

{hex, [
    {repos, [
        #{name => <<"hexpm">>,
          url => <<"https://hex.pm">>,
          public_key => <<"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqREcFDt5vV21JVe2QNB
Edvzk6w36eDководиtA9w5KRhoО8kz7w==
-----END PUBLIC KEY-----">>}
CONFIG_EOF

    # Add working mirrors
    for mirror_name in "${working_mirrors[@]}"; do
        if [ "${mirror_name}" != "hex.pm" ]; then
            cat >> "${config_file}" << CONFIG_EOF
        ,#{name => <<"${mirror_name}">>,
          url => <<"${MIRRORS[$mirror_name]}">>,
          public_key => <<"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqREcFDt5vV21JVe2QNB
Edvzk6w36eDководиtA9w5KRhoО8kz7w==
-----END PUBLIC KEY-----">>}
CONFIG_EOF
        fi
    done
    
    cat >> "${config_file}" << 'CONFIG_EOF'
    ]}
]}.
CONFIG_EOF

    log_success "Config saved to: ${config_file}"
}

# Main test flow
main() {
    log "Starting Hex mirror alternatives test"
    log "Test package: ${TEST_PACKAGE}-${TEST_VERSION}"
    log "Timeout: ${TIMEOUT}s"
    echo ""
    
    # Results storage
    declare -A connectivity_results
    declare -A api_results
    declare -A download_results
    declare -a working_mirrors
    
    # Test each mirror
    for mirror_name in "${!MIRRORS[@]}"; do
        mirror_url="${MIRRORS[$mirror_name]}"
        api_url="${API_ENDPOINTS[$mirror_name]}"
        
        echo ""
        log "========================================="
        log "Testing mirror: ${mirror_name}"
        log "========================================="
        
        # Test 1: Connectivity
        connectivity_time=$(test_mirror_connectivity "${mirror_name}" "${mirror_url}")
        connectivity_results["${mirror_name}"]="${connectivity_time}"
        
        if [ "${connectivity_time}" != "-1" ]; then
            # Test 2: API
            if test_api_endpoint "${mirror_name}" "${api_url}"; then
                api_results["${mirror_name}"]="OK"
                
                # Test 3: Package download
                if download_result=$(test_package_download "${mirror_name}" "${mirror_url}" "${TEST_PACKAGE}" "${TEST_VERSION}"); then
                    download_results["${mirror_name}"]="${download_result}"
                    working_mirrors+=("${mirror_name}")
                else
                    download_results["${mirror_name}"]="FAILED"
                fi
            else
                api_results["${mirror_name}"]="FAILED"
                download_results["${mirror_name}"]="SKIPPED"
            fi
        else
            api_results["${mirror_name}"]="SKIPPED"
            download_results["${mirror_name}"]="SKIPPED"
        fi
    done
    
    # Summary report
    echo ""
    log "========================================="
    log "SUMMARY REPORT"
    log "========================================="
    echo ""
    
    printf "%-20s %-15s %-10s %-20s\n" "Mirror" "Connectivity" "API" "Download" | tee -a "${LOG_DIR}/summary.txt"
    printf "%-20s %-15s %-10s %-20s\n" "------" "------------" "---" "--------" | tee -a "${LOG_DIR}/summary.txt"
    
    for mirror_name in "${!MIRRORS[@]}"; do
        local conn="${connectivity_results[$mirror_name]}"
        local api="${api_results[$mirror_name]}"
        local dl="${download_results[$mirror_name]}"
        
        if [ "${conn}" == "-1" ]; then
            conn="FAILED"
        else
            conn="${conn}ms"
        fi
        
        printf "%-20s %-15s %-10s %-20s\n" "${mirror_name}" "${conn}" "${api}" "${dl}" | tee -a "${LOG_DIR}/summary.txt"
    done
    
    echo ""
    
    # Working mirrors
    if [ ${#working_mirrors[@]} -gt 0 ]; then
        log_success "Working mirrors found: ${working_mirrors[*]}"
        generate_rebar_config "${working_mirrors[@]}"
        
        echo ""
        log "To use alternative mirrors with rebar3:"
        log "  1. Backup current config: cp rebar.config rebar.config.bak"
        log "  2. Add mirror config from: ${PROJECT_ROOT}/rebar.config.mirrors"
        log "  3. Or set HEX_MIRROR environment variable:"
        log "     export HEX_MIRROR=${MIRRORS[${working_mirrors[0]}]}"
    else
        log_error "No working mirrors found!"
        log_warning "Recommendations:"
        log_warning "  1. Check network connectivity"
        log_warning "  2. Verify firewall/proxy settings"
        log_warning "  3. Try git-based dependencies (see git-fallback-test.sh)"
        log_warning "  4. Use manual download (see manual-download.sh)"
    fi
    
    echo ""
    log "Detailed logs: ${LOG_DIR}/test.log"
    log "Test completed at $(date)"
}

# Run main
main "$@"
