#!/usr/bin/env bash
# kerl-otp-manager.sh - Alternative OTP management using Kerl
# Purpose: Install and manage OTP versions with Kerl for better compatibility
# Usage: ./kerl-otp-manager.sh [--install VERSION] [--activate VERSION]

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/log/kerl-manager"

# Kerl installation
KERL_DIR="${HOME}/.kerl"
KERL_BIN="${KERL_DIR}/kerl"
KERL_BUILDS="${KERL_DIR}/builds"
KERL_INSTALLATIONS="${KERL_DIR}/installations"

# OTP versions
OTP_VERSION_DEFAULT="28.3.1"
OTP_VERSION_FALLBACK="27.3"

mkdir -p "${LOG_DIR}" "${KERL_DIR}"

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "${LOG_DIR}/kerl.log"
}

log_success() {
    echo -e "${GREEN}✓${NC} $*" | tee -a "${LOG_DIR}/kerl.log"
}

log_error() {
    echo -e "${RED}✗${NC} $*" | tee -a "${LOG_DIR}/kerl.log"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $*" | tee -a "${LOG_DIR}/kerl.log"
}

# Install kerl
install_kerl() {
    log "Installing kerl"
    
    if [ -f "${KERL_BIN}" ]; then
        log_success "Kerl already installed: ${KERL_BIN}"
        return 0
    fi
    
    # Download kerl
    local kerl_url="https://raw.githubusercontent.com/kerl/kerl/master/kerl"
    
    if curl -s -f -L -o "${KERL_BIN}" "${kerl_url}"; then
        chmod +x "${KERL_BIN}"
        log_success "Kerl installed: ${KERL_BIN}"
        
        # Configure kerl
        configure_kerl
        
        return 0
    else
        log_error "Failed to download kerl"
        return 1
    fi
}

# Configure kerl options
configure_kerl() {
    log "Configuring kerl"
    
    local kerl_config="${HOME}/.kerlrc"
    
    cat > "${kerl_config}" << 'CONFIG_EOF'
# Kerl configuration
# Generated by kerl-otp-manager.sh

# Build options
KERL_CONFIGURE_OPTIONS="--disable-debug \
    --disable-silent-rules \
    --enable-shared-zlib \
    --enable-dynamic-ssl-lib \
    --enable-hipe \
    --enable-sctp \
    --enable-smp-support \
    --enable-threads \
    --enable-kernel-poll \
    --enable-wx \
    --enable-darwin-64bit"

# Installation directory
KERL_BUILD_BACKEND=git

# Enable documentation
KERL_BUILD_DOCS=yes
KERL_INSTALL_MANPAGES=yes
KERL_INSTALL_HTMLDOCS=yes

# Parallel builds
MAKEFLAGS="-j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)"
CONFIG_EOF

    log_success "Kerl config created: ${kerl_config}"
}

# List available OTP releases
list_available_releases() {
    log "Fetching available OTP releases"
    
    "${KERL_BIN}" update releases
    
    log "Available releases:"
    "${KERL_BIN}" list releases | tail -20 | tee -a "${LOG_DIR}/kerl.log"
}

# List installed OTP versions
list_installed() {
    log "Installed OTP versions:"
    
    if "${KERL_BIN}" list installations | grep -q "No"; then
        log_warning "No installations found"
        return 1
    else
        "${KERL_BIN}" list installations | tee -a "${LOG_DIR}/kerl.log"
        return 0
    fi
}

# Build OTP version
build_otp() {
    local version="$1"
    local build_name="OTP-${version}"
    
    log "Building OTP ${version}"
    log "This may take 15-30 minutes..."
    
    # Check if already built
    if "${KERL_BIN}" list builds | grep -q "${build_name}"; then
        log_success "Build already exists: ${build_name}"
        return 0
    fi
    
    # Build
    log "Starting build (see ${LOG_DIR}/build-${version}.log for details)"
    
    if "${KERL_BIN}" build "${version}" "${build_name}" 2>&1 | tee "${LOG_DIR}/build-${version}.log"; then
        log_success "Build completed: ${build_name}"
        return 0
    else
        log_error "Build failed for OTP ${version}"
        log "Check log: ${LOG_DIR}/build-${version}.log"
        return 1
    fi
}

# Install OTP version
install_otp() {
    local version="$1"
    local build_name="OTP-${version}"
    local install_dir="${KERL_INSTALLATIONS}/${version}"
    
    log "Installing OTP ${version}"
    
    # Check if already installed
    if [ -d "${install_dir}" ]; then
        log_success "Already installed: ${install_dir}"
        return 0
    fi
    
    # Ensure build exists
    if ! "${KERL_BIN}" list builds | grep -q "${build_name}"; then
        log_warning "Build not found, building first"
        if ! build_otp "${version}"; then
            return 1
        fi
    fi
    
    # Install
    log "Installing to ${install_dir}"
    
    if "${KERL_BIN}" install "${build_name}" "${install_dir}" 2>&1 | tee "${LOG_DIR}/install-${version}.log"; then
        log_success "Installation completed: ${install_dir}"
        
        # Create activation script
        create_activation_script "${version}" "${install_dir}"
        
        return 0
    else
        log_error "Installation failed for OTP ${version}"
        return 1
    fi
}

# Create activation script
create_activation_script() {
    local version="$1"
    local install_dir="$2"
    local activate_script="${PROJECT_ROOT}/activate-otp-${version}.sh"
    
    cat > "${activate_script}" << ACTIVATE_EOF
#!/usr/bin/env bash
# Activate OTP ${version} (installed via kerl)
# Source this file: source ${activate_script}

if [ -f "${install_dir}/activate" ]; then
    source "${install_dir}/activate"
    echo "Activated OTP ${version}"
    echo "Erlang: \$(erl -version 2>&1 | head -1)"
    echo "Install dir: ${install_dir}"
else
    echo "ERROR: Activation script not found: ${install_dir}/activate"
    return 1
fi
ACTIVATE_EOF

    chmod +x "${activate_script}"
    log_success "Created activation script: ${activate_script}"
}

# Activate OTP version
activate_otp() {
    local version="$1"
    local install_dir="${KERL_INSTALLATIONS}/${version}"
    
    if [ ! -d "${install_dir}" ]; then
        log_error "OTP ${version} not installed"
        log "Run: $0 --install ${version}"
        return 1
    fi
    
    log "Activating OTP ${version}"
    
    if [ -f "${install_dir}/activate" ]; then
        # Show activation command
        log "To activate, run:"
        log "  source ${install_dir}/activate"
        log ""
        log "Or use the convenience script:"
        log "  source ${PROJECT_ROOT}/activate-otp-${version}.sh"
        
        return 0
    else
        log_error "Activation script not found"
        return 1
    fi
}

# Test OTP installation with rebar3
test_with_rebar3() {
    local version="$1"
    local install_dir="${KERL_INSTALLATIONS}/${version}"
    
    log "Testing OTP ${version} with rebar3"
    
    # Activate OTP
    if [ -f "${install_dir}/activate" ]; then
        source "${install_dir}/activate"
        
        log "Erlang version:"
        erl -version 2>&1 | tee -a "${LOG_DIR}/kerl.log"
        
        # Test rebar3
        cd "${PROJECT_ROOT}"
        
        log "Cleaning build"
        rm -rf _build
        
        log "Testing compilation"
        if TERM=dumb rebar3 compile 2>&1 | tee "${LOG_DIR}/rebar3-test-${version}.log"; then
            log_success "rebar3 compile successful with OTP ${version}"
            return 0
        else
            log_error "rebar3 compile failed with OTP ${version}"
            log "Check log: ${LOG_DIR}/rebar3-test-${version}.log"
            return 1
        fi
    else
        log_error "Could not activate OTP ${version}"
        return 1
    fi
}

# Compare kerl vs system OTP
compare_installations() {
    log "========================================="
    log "OTP Installation Comparison"
    log "========================================="
    
    # System OTP
    if command -v erl >/dev/null 2>&1; then
        log "System OTP:"
        erl -version 2>&1 | tee -a "${LOG_DIR}/kerl.log"
        log "  Location: $(command -v erl)"
    else
        log_warning "No system OTP found"
    fi
    
    echo ""
    
    # Kerl installations
    log "Kerl installations:"
    if list_installed; then
        for install in "${KERL_INSTALLATIONS}"/*; do
            if [ -d "${install}" ]; then
                local version=$(basename "${install}")
                local bin_dir="${install}/bin"
                
                if [ -f "${bin_dir}/erl" ]; then
                    log "  OTP ${version}:"
                    "${bin_dir}/erl" -version 2>&1 | head -1 | tee -a "${LOG_DIR}/kerl.log"
                    log "    Location: ${install}"
                fi
            fi
        done
    fi
}

# Uninstall OTP version
uninstall_otp() {
    local version="$1"
    local install_dir="${KERL_INSTALLATIONS}/${version}"
    
    log "Uninstalling OTP ${version}"
    
    if [ ! -d "${install_dir}" ]; then
        log_error "OTP ${version} not installed"
        return 1
    fi
    
    if "${KERL_BIN}" delete installation "${install_dir}"; then
        log_success "Uninstalled OTP ${version}"
        
        # Remove activation script
        rm -f "${PROJECT_ROOT}/activate-otp-${version}.sh"
        
        return 0
    else
        log_error "Failed to uninstall OTP ${version}"
        return 1
    fi
}

# Show status
show_status() {
    log "========================================="
    log "Kerl Status"
    log "========================================="
    
    log "Kerl binary: ${KERL_BIN}"
    log "Builds directory: ${KERL_BUILDS}"
    log "Installations directory: ${KERL_INSTALLATIONS}"
    
    echo ""
    
    log "Available builds:"
    "${KERL_BIN}" list builds 2>/dev/null | tee -a "${LOG_DIR}/kerl.log" || log "No builds"
    
    echo ""
    
    log "Installed versions:"
    list_installed || true
    
    echo ""
    
    compare_installations
}

# Main
main() {
    log "Kerl OTP Manager"
    
    # Ensure kerl is installed
    if [ ! -f "${KERL_BIN}" ]; then
        install_kerl
    fi
    
    local action="status"
    local version="${OTP_VERSION_DEFAULT}"
    
    while [ $# -gt 0 ]; do
        case "$1" in
            --install)
                action="install"
                version="${2:-${OTP_VERSION_DEFAULT}}"
                shift 2
                ;;
            --activate)
                action="activate"
                version="${2:-${OTP_VERSION_DEFAULT}}"
                shift 2
                ;;
            --test)
                action="test"
                version="${2:-${OTP_VERSION_DEFAULT}}"
                shift 2
                ;;
            --uninstall)
                action="uninstall"
                version="${2:-${OTP_VERSION_DEFAULT}}"
                shift 2
                ;;
            --list)
                action="list"
                shift
                ;;
            --status)
                action="status"
                shift
                ;;
            --compare)
                action="compare"
                shift
                ;;
            *)
                log_error "Unknown option: $1"
                cat << 'HELP_EOF'
Usage: kerl-otp-manager.sh [OPTIONS]

Options:
  --install VERSION    Build and install OTP version
  --activate VERSION   Activate installed OTP version
  --test VERSION       Test OTP version with rebar3
  --uninstall VERSION  Remove OTP installation
  --list              List available OTP releases
  --status            Show kerl status
  --compare           Compare kerl vs system OTP

Examples:
  ./kerl-otp-manager.sh --install 28.3.1
  ./kerl-otp-manager.sh --activate 28.3.1
  ./kerl-otp-manager.sh --test 28.3.1
  ./kerl-otp-manager.sh --status
HELP_EOF
                exit 1
                ;;
        esac
    done
    
    case "${action}" in
        install)
            build_otp "${version}"
            install_otp "${version}"
            activate_otp "${version}"
            ;;
        activate)
            activate_otp "${version}"
            ;;
        test)
            test_with_rebar3 "${version}"
            ;;
        uninstall)
            uninstall_otp "${version}"
            ;;
        list)
            list_available_releases
            ;;
        status)
            show_status
            ;;
        compare)
            compare_installations
            ;;
    esac
    
    log "Completed at $(date)"
    log "Logs: ${LOG_DIR}/kerl.log"
}

main "$@"
