#!/usr/bin/env bash
# offline-package-test.sh - Test offline package installation
# Purpose: Create local hex repository and test offline builds
# Usage: ./offline-package-test.sh [--create-repo] [--test-offline]

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOG_DIR="${PROJECT_ROOT}/log/offline-test"
OFFLINE_REPO_DIR="${PROJECT_ROOT}/.offline-hex-repo"
OFFLINE_PACKAGES_DIR="${OFFLINE_REPO_DIR}/packages"
OFFLINE_TARBALLS_DIR="${OFFLINE_REPO_DIR}/tarballs"

mkdir -p "${LOG_DIR}" "${OFFLINE_PACKAGES_DIR}" "${OFFLINE_TARBALLS_DIR}"

log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*" | tee -a "${LOG_DIR}/offline.log"
}

log_success() {
    echo -e "${GREEN}✓${NC} $*" | tee -a "${LOG_DIR}/offline.log"
}

log_error() {
    echo -e "${RED}✗${NC} $*" | tee -a "${LOG_DIR}/offline.log"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $*" | tee -a "${LOG_DIR}/offline.log"
}

# Create local hex repository structure
create_local_repo() {
    log "Creating local hex repository"
    log "Location: ${OFFLINE_REPO_DIR}"
    
    # Create directory structure
    mkdir -p "${OFFLINE_PACKAGES_DIR}"
    mkdir -p "${OFFLINE_TARBALLS_DIR}"
    
    # Copy from hex cache if it exists
    local hex_cache="${HOME}/.cache/rebar3/hex/default"
    
    if [ -d "${hex_cache}/tarballs" ]; then
        log "Copying from hex cache: ${hex_cache}"
        
        local count=0
        for tarball in "${hex_cache}/tarballs"/*.tar; do
            if [ -f "${tarball}" ]; then
                cp "${tarball}" "${OFFLINE_TARBALLS_DIR}/"
                ((count++))
            fi
        done
        
        log_success "Copied ${count} packages from cache"
    else
        log_warning "No hex cache found, will download packages"
    fi
    
    # Create repository index
    create_repo_index
    
    log_success "Local repository created"
}

# Create repository index file
create_repo_index() {
    local index_file="${OFFLINE_REPO_DIR}/packages.idx"
    
    log "Creating repository index"
    
    # List all tarballs
    > "${index_file}"
    
    for tarball in "${OFFLINE_TARBALLS_DIR}"/*.tar; do
        if [ -f "${tarball}" ]; then
            local basename=$(basename "${tarball}" .tar)
            echo "${basename}" >> "${index_file}"
        fi
    done
    
    local count=$(wc -l < "${index_file}")
    log_success "Indexed ${count} packages"
}

# Download missing packages
download_missing_packages() {
    local lock_file="${PROJECT_ROOT}/rebar.lock"
    
    if [ ! -f "${lock_file}" ]; then
        log_error "rebar.lock not found"
        return 1
    fi
    
    log "Checking for missing packages"
    
    # Parse rebar.lock
    local packages
    packages=$(grep -o '<<"[^"]*">>,{pkg,<<"[^"]*">>,<<"[^"]*">>}' "${lock_file}" | \
               sed 's/<<"//g; s/">>//g; s/,{pkg,/ /g')
    
    local downloaded=0
    
    while IFS= read -r line; do
        if [ -n "${line}" ]; then
            local package=$(echo "${line}" | awk '{print $1}')
            local version=$(echo "${line}" | awk '{print $2}')
            local tarball="${OFFLINE_TARBALLS_DIR}/${package}-${version}.tar"
            
            if [ ! -f "${tarball}" ]; then
                log "Downloading ${package}-${version}"
                
                local url="https://repo.hex.pm/tarballs/${package}-${version}.tar"
                if curl -s -f -L -o "${tarball}" "${url}"; then
                    log_success "Downloaded ${package}-${version}"
                    ((downloaded++))
                else
                    log_error "Failed to download ${package}-${version}"
                    rm -f "${tarball}"
                fi
            fi
        fi
    done <<< "${packages}"
    
    if [ ${downloaded} -gt 0 ]; then
        log_success "Downloaded ${downloaded} missing packages"
        create_repo_index
    else
        log "No missing packages"
    fi
}

# Configure rebar3 for offline mode
configure_offline_mode() {
    log "Configuring rebar3 for offline mode"
    
    # Create rebar3 hex config
    local hex_config="${HOME}/.config/rebar3/hex.config"
    local hex_config_backup="${hex_config}.backup.$(date +%Y%m%d_%H%M%S)"
    
    mkdir -p "$(dirname ${hex_config})"
    
    # Backup existing config
    if [ -f "${hex_config}" ]; then
        cp "${hex_config}" "${hex_config_backup}"
        log "Backed up hex config to ${hex_config_backup}"
    fi
    
    # Create offline config
    cat > "${hex_config}" << CONFIG_EOF
%% Offline hex configuration
%% Generated by offline-package-test.sh

{offline, true}.

{repos, [
    #{name => <<"hexpm">>,
      url => <<"file://${OFFLINE_REPO_DIR}">>,
      public_key => undefined,
      auth_key => undefined}
]}.

{http_options, [
    {timeout, 60000},
    {connect_timeout, 30000}
]}.
CONFIG_EOF

    log_success "Created offline config: ${hex_config}"
    
    # Set environment variable
    export HEX_OFFLINE=true
    export HEX_HOME="${OFFLINE_REPO_DIR}"
    
    log "Environment configured:"
    log "  HEX_OFFLINE=true"
    log "  HEX_HOME=${OFFLINE_REPO_DIR}"
}

# Test offline build
test_offline_build() {
    log "========================================="
    log "Testing offline build"
    log "========================================="
    
    cd "${PROJECT_ROOT}"
    
    # Clean build
    log "Cleaning build directory"
    rm -rf _build
    
    # Configure offline mode
    configure_offline_mode
    
    # Set rebar3 to use local cache
    export REBAR_CACHE_DIR="${OFFLINE_REPO_DIR}"
    
    log "Attempting offline compilation"
    
    # Try compile
    if TERM=dumb rebar3 compile 2>&1 | tee "${LOG_DIR}/offline-build.log"; then
        log_success "Offline build successful!"
        return 0
    else
        log_error "Offline build failed"
        log "Check log: ${LOG_DIR}/offline-build.log"
        
        # Show missing packages
        log "Missing packages:"
        grep -i "failed" "${LOG_DIR}/offline-build.log" | grep -o '[a-z_]*-[0-9.]*' || true
        
        return 1
    fi
}

# Create portable package bundle
create_portable_bundle() {
    log "Creating portable package bundle"
    
    local bundle_file="${PROJECT_ROOT}/hex-packages-bundle-$(date +%Y%m%d).tar.gz"
    
    cd "${OFFLINE_REPO_DIR}"
    
    if tar -czf "${bundle_file}" .; then
        local size=$(stat -f%z "${bundle_file}" 2>/dev/null || stat -c%s "${bundle_file}" 2>/dev/null || echo "0")
        local size_mb=$((size / 1024 / 1024))
        
        log_success "Bundle created: ${bundle_file}"
        log "Size: ${size_mb}MB"
        
        # Create README
        cat > "${PROJECT_ROOT}/hex-bundle-README.txt" << 'README_EOF'
Hex Packages Offline Bundle
============================

This bundle contains all hex packages needed to build erlmcp offline.

Installation:
1. Extract bundle:
   tar -xzf hex-packages-bundle-YYYYMMDD.tar.gz -C ~/.cache/rebar3/hex/default/

2. Set offline mode:
   export HEX_OFFLINE=true
   export REBAR_CACHE_DIR=~/.cache/rebar3/hex/default

3. Build:
   rebar3 compile

Verification:
- Check cache: ls ~/.cache/rebar3/hex/default/tarballs/
- Test build: TERM=dumb rebar3 clean && rebar3 compile
README_EOF

        log_success "Created README: ${PROJECT_ROOT}/hex-bundle-README.txt"
        
        return 0
    else
        log_error "Failed to create bundle"
        return 1
    fi
}

# Verify package integrity
verify_packages() {
    log "Verifying package integrity"
    
    local verified=0
    local failed=0
    
    for tarball in "${OFFLINE_TARBALLS_DIR}"/*.tar; do
        if [ -f "${tarball}" ]; then
            if tar -tzf "${tarball}" >/dev/null 2>&1; then
                ((verified++))
            else
                log_error "Corrupted: $(basename ${tarball})"
                ((failed++))
            fi
        fi
    done
    
    log "Verified: ${verified} packages"
    if [ ${failed} -gt 0 ]; then
        log_error "Failed: ${failed} packages"
        return 1
    fi
    
    return 0
}

# Show repository status
show_repo_status() {
    log "========================================="
    log "Repository Status"
    log "========================================="
    
    local tarball_count=$(find "${OFFLINE_TARBALLS_DIR}" -name "*.tar" 2>/dev/null | wc -l)
    local total_size=$(du -sh "${OFFLINE_REPO_DIR}" 2>/dev/null | awk '{print $1}')
    
    log "Location: ${OFFLINE_REPO_DIR}"
    log "Packages: ${tarball_count}"
    log "Total size: ${total_size}"
    
    echo ""
    log "Recent packages:"
    ls -lht "${OFFLINE_TARBALLS_DIR}"/*.tar 2>/dev/null | head -10 || log "No packages found"
}

# Main
main() {
    log "Starting offline package test"
    
    local action="all"
    
    while [ $# -gt 0 ]; do
        case "$1" in
            --create-repo)
                action="create"
                shift
                ;;
            --test-offline)
                action="test"
                shift
                ;;
            --status)
                action="status"
                shift
                ;;
            --bundle)
                action="bundle"
                shift
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Usage: $0 [--create-repo|--test-offline|--status|--bundle]"
                exit 1
                ;;
        esac
    done
    
    case "${action}" in
        create)
            create_local_repo
            download_missing_packages
            verify_packages
            show_repo_status
            ;;
        test)
            test_offline_build
            ;;
        status)
            show_repo_status
            ;;
        bundle)
            create_portable_bundle
            ;;
        all)
            create_local_repo
            download_missing_packages
            verify_packages
            show_repo_status
            
            echo ""
            read -p "Test offline build? (y/n) " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                test_offline_build
            fi
            
            echo ""
            read -p "Create portable bundle? (y/n) " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                create_portable_bundle
            fi
            ;;
    esac
    
    log "Completed at $(date)"
    log "Logs: ${LOG_DIR}/offline.log"
}

main "$@"
