%% ============================================================================
%% sys.config - Erlang System Configuration for erlmcp
%% ============================================================================
%% Generated by Terraform for ${environment} environment
%%
%% DOCKER-ONLY CONSTITUTION: Configuration is validated at build time.
%% ============================================================================

[
  %% -------------------------------------------------------------------------
  %% erlmcp Application Configuration
  %% -------------------------------------------------------------------------
  {erlmcp, [
    %% Environment
    {environment, ${environment}},
    {node_role, ${node_role}},

    %% Transport Configuration
    {transports, [
      %% STDIO transport (for CLI/subprocess integration)
      {stdio, [
        {enabled, ${stdio_enabled}},
        {buffer_size, ${stdio_buffer_size}}
      ]},

      %% TCP transport
      {tcp, [
        {enabled, ${tcp_enabled}},
        {port, ${tcp_port}},
        {acceptors, ${tcp_acceptors}},
        {max_connections, ${tcp_max_connections}},
        {socket_opts, [
          {reuseaddr, true},
          {nodelay, true},
          {keepalive, true},
          {backlog, ${tcp_backlog}}
        ]}
      ]},

      %% HTTP transport (REST API + WebSocket + SSE)
      {http, [
        {enabled, ${http_enabled}},
        {port, ${http_port}},
        {acceptors, ${http_acceptors}},
        {max_connections, ${http_max_connections}},
        {idle_timeout, ${http_idle_timeout}},
        {request_timeout, ${http_request_timeout}},
        {websocket, [
          {enabled, ${ws_enabled}},
          {path, "/ws"},
          {ping_interval, ${ws_ping_interval}}
        ]},
        {sse, [
          {enabled, ${sse_enabled}},
          {path, "/events"},
          {heartbeat_interval, ${sse_heartbeat_interval}}
        ]}
      ]}
    ]},

    %% MCP Protocol Configuration
    {protocol, [
      {version, "2024-11-05"},
      {capabilities, [
        {tools, ${tools_enabled}},
        {resources, ${resources_enabled}},
        {prompts, ${prompts_enabled}},
        {sampling, ${sampling_enabled}},
        {logging, ${logging_enabled}}
      ]},
      {request_timeout, ${request_timeout}},
      {max_request_size, ${max_request_size}}
    ]},

    %% Registry Configuration (gproc-based)
    {registry, [
      {backend, gproc},
      {cleanup_interval, ${registry_cleanup_interval}}
    ]},

    %% Session Management
    {sessions, [
      {max_sessions, ${max_sessions}},
      {session_timeout, ${session_timeout}},
      {heartbeat_interval, ${session_heartbeat_interval}}
    ]},

    %% Backpressure Configuration
    {backpressure, [
      {enabled, true},
      {max_queue_size, ${max_queue_size}},
      {high_watermark, ${high_watermark}},
      {low_watermark, ${low_watermark}}
    ]},

    %% Health Check Endpoint
    {health, [
      {enabled, true},
      {port, ${health_port}},
      {path, "/health"}
    ]},

    %% Metrics Endpoint
    {metrics, [
      {enabled, ${metrics_enabled}},
      {port, ${metrics_port}},
      {path, "/metrics"}
    ]}
  ]},

  %% -------------------------------------------------------------------------
  %% Kernel Configuration
  %% -------------------------------------------------------------------------
  {kernel, [
    %% Logger Configuration
    {logger_level, ${log_level}},
    {logger, [
      %% Default handler - JSON structured logging
      {handler, default, logger_std_h, #{
        level => ${log_level},
        config => #{
          type => standard_io
        },
        formatter => {logger_formatter, #{
          template => [time, " ", level, " ", pid, " ", mfa, " ", msg, "\n"],
          single_line => true,
          time_designator => $T
        }}
      }},

      %% File handler for persistent logs
      {handler, file_handler, logger_std_h, #{
        level => ${log_level},
        config => #{
          file => "${log_dir}/erlmcp.log",
          max_no_bytes => ${log_max_bytes},
          max_no_files => ${log_max_files},
          type => file
        },
        formatter => {logger_formatter, #{
          template => [time, " ", level, " ", pid, " ", mfa, " ", msg, "\n"],
          single_line => true
        }}
      }},

      %% Error handler for error.log
      {handler, error_handler, logger_std_h, #{
        level => error,
        config => #{
          file => "${log_dir}/error.log",
          max_no_bytes => ${log_max_bytes},
          max_no_files => ${log_max_files},
          type => file
        },
        filters => [{error_only, {fun logger_filters:level/2, {stop, lt, error}}}]
      }}
    ]},

    %% Network Kernel Settings
    {inet_dist_listen_min, ${dist_port_min}},
    {inet_dist_listen_max, ${dist_port_max}},
    {net_ticktime, ${net_ticktime}},

    %% Prevent shell from starting in daemon mode
    {shell_history, disabled}
  ]},

  %% -------------------------------------------------------------------------
  %% SASL Configuration
  %% -------------------------------------------------------------------------
  {sasl, [
    {sasl_error_logger, false},
    {errlog_type, error}
  ]},

  %% -------------------------------------------------------------------------
  %% SSL/TLS Configuration
  %% -------------------------------------------------------------------------
  {ssl, [
    {session_lifetime, 3600},
    {protocol_version, ['tlsv1.3', 'tlsv1.2']}
  ]},

  %% -------------------------------------------------------------------------
  %% gproc Registry Configuration
  %% -------------------------------------------------------------------------
  {gproc, [
    {gproc_dist, ${gproc_dist_mode}}
  ]},

  %% -------------------------------------------------------------------------
  %% Telemetry/OpenTelemetry Configuration
  %% -------------------------------------------------------------------------
  {opentelemetry, [
    {span_processor, batch},
    {traces_exporter, ${otel_exporter}},
    {resource, #{
      service => #{name => <<"erlmcp">>, version => <<"${app_version}">>},
      deployment => #{environment => <<"${environment}">>},
      cloud => #{
        provider => <<"aws">>,
        region => <<"${aws_region}">>
      }
    }}
  ]},

  {opentelemetry_exporter, [
    {otlp_protocol, grpc},
    {otlp_endpoint, "${otel_endpoint}"}
  ]},

  %% -------------------------------------------------------------------------
  %% AWS SDK Configuration
  %% -------------------------------------------------------------------------
  {erlcloud, [
    {aws_region, "${aws_region}"}
  ]},

  %% -------------------------------------------------------------------------
  %% Database Configuration (if applicable)
  %% -------------------------------------------------------------------------
  {erlmcp_db, [
    {enabled, ${db_enabled}},
    {pool_size, ${db_pool_size}},
    {host, "${db_host}"},
    {port, ${db_port}},
    {database, "${db_name}"},
    {username, "${db_username}"},
    %% Password fetched from Secrets Manager at runtime
    {password, {env, "DB_PASSWORD"}}
  ]},

  %% -------------------------------------------------------------------------
  %% Cache Configuration (Redis/Memorystore)
  %% -------------------------------------------------------------------------
  {erlmcp_cache, [
    {enabled, ${cache_enabled}},
    {backend, redis},
    {host, "${cache_host}"},
    {port, ${cache_port}},
    {pool_size, ${cache_pool_size}},
    {ttl_seconds, ${cache_ttl}}
  ]}
].
