#!/bin/bash
# ============================================================================
# erlmcp EC2 Instance Bootstrap Script
# ============================================================================
# This cloud-init script runs on instance launch to:
#   - Configure the CloudWatch Agent for logging
#   - Fetch secrets from SSM Parameter Store
#   - Configure the Erlang VM
#   - Start the erlmcp application
#
# The AMI already contains:
#   - Erlang/OTP runtime
#   - erlmcp release in /opt/erlmcp
#   - systemd service file
#
# DOCKER-ONLY CONSTITUTION: No compilation here - AMI is pre-baked.
# ============================================================================

set -euo pipefail

# Logging
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting bootstrap..."

# ============================================================================
# Variables from Terraform
# ============================================================================
ENVIRONMENT="${environment}"
AWS_REGION="${region}"
LOG_GROUP="${log_group}"
APP_PORT="${app_port}"
METRICS_PORT="${metrics_port}"

# Instance metadata (IMDSv2)
TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/instance-id)
PRIVATE_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/local-ipv4)
AZ=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/placement/availability-zone)

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Instance: $INSTANCE_ID in $AZ"

# ============================================================================
# Configure CloudWatch Agent
# ============================================================================
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Configuring CloudWatch Agent..."

cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<EOF
{
  "agent": {
    "metrics_collection_interval": 60,
    "run_as_user": "root"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/erlmcp/console.log",
            "log_group_name": "$LOG_GROUP",
            "log_stream_name": "{instance_id}/console",
            "retention_in_days": 30
          },
          {
            "file_path": "/var/log/erlmcp/error.log",
            "log_group_name": "$LOG_GROUP",
            "log_stream_name": "{instance_id}/error",
            "retention_in_days": 30
          },
          {
            "file_path": "/var/log/messages",
            "log_group_name": "$LOG_GROUP",
            "log_stream_name": "{instance_id}/syslog",
            "retention_in_days": 30
          }
        ]
      }
    }
  },
  "metrics": {
    "namespace": "erlmcp/$ENVIRONMENT",
    "metrics_collected": {
      "cpu": {
        "measurement": ["cpu_usage_active", "cpu_usage_idle"],
        "metrics_collection_interval": 60
      },
      "disk": {
        "measurement": ["disk_used_percent"],
        "metrics_collection_interval": 60,
        "resources": ["/"]
      },
      "mem": {
        "measurement": ["mem_used_percent"],
        "metrics_collection_interval": 60
      },
      "net": {
        "measurement": ["net_bytes_recv", "net_bytes_sent"],
        "metrics_collection_interval": 60
      }
    }
  }
}
EOF

# Start CloudWatch Agent
systemctl enable amazon-cloudwatch-agent
systemctl restart amazon-cloudwatch-agent

# ============================================================================
# Fetch Secrets from SSM Parameter Store
# ============================================================================
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Fetching secrets from SSM..."

# Erlang cookie
ERLANG_COOKIE=$(aws ssm get-parameter \
  --name "/erlmcp/$ENVIRONMENT/erlang_cookie" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --region "$AWS_REGION" 2>/dev/null || echo "erlmcp_default_cookie")

# Database password (if needed)
DB_PASSWORD=$(aws ssm get-parameter \
  --name "/erlmcp/$ENVIRONMENT/db_password" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --region "$AWS_REGION" 2>/dev/null || echo "")

# ============================================================================
# Configure Erlang VM
# ============================================================================
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Configuring Erlang VM..."

# Generate node name based on private IP
NODE_NAME="erlmcp@$PRIVATE_IP"

# Create vm.args
cat > /opt/erlmcp/releases/3.0.0/vm.args <<EOF
## vm.args - Generated by cloud-init
## Instance: $INSTANCE_ID
## Environment: $ENVIRONMENT

-name $NODE_NAME
-setcookie $ERLANG_COOKIE

## VM Tuning
+P 256000
+Q 65536
+A 10
+K true
+sbwt very_short
+swt very_low

## Memory
+MBas ageffcbf
+MHas ageffcbf
+MMmcs 30

## Scheduler
+S 4:4
+SDcpu 50
+SDio 50

## Kernel
-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9200

## Heart (VM watchdog)
-heart
-env HEART_BEAT_TIMEOUT 60
-env HEART_COMMAND "/opt/erlmcp/bin/erlmcp restart"
EOF

# Create environment file for systemd
cat > /etc/erlmcp/environment <<EOF
# erlmcp Environment Configuration
# Generated by cloud-init on $INSTANCE_ID

ERLMCP_ENV=$ENVIRONMENT
ERLMCP_PORT=$APP_PORT
ERLMCP_METRICS_PORT=$METRICS_PORT
ERLMCP_NODE_NAME=$NODE_NAME
ERLMCP_LOG_LEVEL=info

# AWS Configuration
AWS_REGION=$AWS_REGION

# Database (if applicable)
DB_PASSWORD=$DB_PASSWORD
EOF

chmod 600 /etc/erlmcp/environment

# ============================================================================
# Create Log Directory
# ============================================================================
mkdir -p /var/log/erlmcp
chown erlmcp:erlmcp /var/log/erlmcp

# ============================================================================
# Start Application
# ============================================================================
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting erlmcp service..."

systemctl daemon-reload
systemctl enable erlmcp
systemctl start erlmcp

# Wait for application to be ready
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Waiting for application to be healthy..."
for i in {1..30}; do
  if curl -sf "http://localhost:$APP_PORT/health" > /dev/null 2>&1; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Application is healthy!"
    break
  fi
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Waiting... ($i/30)"
  sleep 2
done

# Signal completion to ASG lifecycle hook (if needed)
if command -v aws &> /dev/null; then
  # Get the lifecycle hook token if this is a scale-out event
  LIFECYCLE_TOKEN=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
    http://169.254.169.254/latest/meta-data/tags/instance/aws:autoscaling:lifecycleState 2>/dev/null || echo "")

  if [ "$LIFECYCLE_TOKEN" = "Pending:Wait" ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Completing lifecycle hook..."
    aws autoscaling complete-lifecycle-action \
      --lifecycle-action-result CONTINUE \
      --instance-id "$INSTANCE_ID" \
      --lifecycle-hook-name startup-hook \
      --auto-scaling-group-name "erlmcp-$ENVIRONMENT-asg" \
      --region "$AWS_REGION" || true
  fi
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Bootstrap complete!"
