## ============================================================================
## vm.args - Erlang VM Arguments for erlmcp
## ============================================================================
## Generated by Terraform/cloud-init for ${environment} environment
## Node: ${node_name}
##
## DOCKER-ONLY CONSTITUTION: This file is baked into AMI or injected by ECS.
## ============================================================================

## -----------------------------------------------------------------------------
## Node Identity
## -----------------------------------------------------------------------------

## Node name: erlmcp@<private-ip> for clustered deployments
-name ${node_name}

## Distribution cookie for cluster authentication
## SECURITY: Cookie is fetched from SSM Parameter Store at boot time
-setcookie ${erlang_cookie}

## -----------------------------------------------------------------------------
## Scheduler Configuration
## -----------------------------------------------------------------------------

## Number of scheduler threads (match vCPUs)
+S ${schedulers}:${schedulers}

## Scheduler busy wait threshold (very_short for low latency)
+sbwt very_short

## Scheduler wake threshold
+swt very_low

## Dirty CPU schedulers utilization (50% for mixed workloads)
+SDcpu ${dirty_cpu_schedulers_online}

## Dirty IO schedulers
+SDio ${dirty_io_schedulers}

## -----------------------------------------------------------------------------
## Process and Port Limits
## -----------------------------------------------------------------------------

## Maximum number of processes (256K default, increase for high concurrency)
+P ${max_processes}

## Maximum number of ports (65K default)
+Q ${max_ports}

## Maximum number of ETS tables
+e ${max_ets_tables}

## -----------------------------------------------------------------------------
## Memory Allocator Configuration
## -----------------------------------------------------------------------------

## Carrier migration: ageffcbf = aggressive carrier migration
+MBas ageffcbf
+MHas ageffcbf

## Maximum memory carrier size
+MMmcs ${max_carrier_size}

## Binary virtual heap size
+MBbs ${binary_vheap_size}

## Carrier pool size for sys_alloc
+MIscs ${carrier_pool_size}

## -----------------------------------------------------------------------------
## Async Thread Pool
## -----------------------------------------------------------------------------

## Async threads for file I/O (default 10, increase for disk-heavy workloads)
+A ${async_threads}

## -----------------------------------------------------------------------------
## Kernel Poll
## -----------------------------------------------------------------------------

## Enable kernel poll (epoll on Linux) for efficient I/O
+K true

## -----------------------------------------------------------------------------
## Distribution Configuration
## -----------------------------------------------------------------------------

## Port range for distributed Erlang connections
-kernel inet_dist_listen_min ${dist_port_min}
-kernel inet_dist_listen_max ${dist_port_max}

## Distribution buffer busy limit (16MB for large messages)
+zdbbl ${dist_buffer_busy_limit}

## -----------------------------------------------------------------------------
## Heart - Erlang Watchdog
## -----------------------------------------------------------------------------

## Enable heart for automatic VM restart on crash
${heart_enabled}

## Heart beat timeout in seconds
-env HEART_BEAT_TIMEOUT ${heart_timeout}

## Command to run on heart failure
-env HEART_COMMAND "${heart_command}"

## -----------------------------------------------------------------------------
## Embedded Mode
## -----------------------------------------------------------------------------

## Run in embedded mode for production (code is pre-loaded)
${embedded_mode}

## -----------------------------------------------------------------------------
## Time Warp Mode
## -----------------------------------------------------------------------------

## Enable multi-time warp for better time handling
+C multi_time_warp

## -----------------------------------------------------------------------------
## SMP Configuration
## -----------------------------------------------------------------------------

## Enable SMP (symmetric multiprocessing)
-smp auto

## -----------------------------------------------------------------------------
## Crash Dump Configuration
## -----------------------------------------------------------------------------

## Crash dump location
-env ERL_CRASH_DUMP ${crash_dump_path}

## Maximum crash dump size (1GB)
-env ERL_CRASH_DUMP_BYTES ${crash_dump_bytes}

## -----------------------------------------------------------------------------
## Environment-Specific Settings
## -----------------------------------------------------------------------------

## Log level (emergency|alert|critical|error|warning|notice|info|debug)
-kernel logger_level ${log_level}

## Environment identifier
-erlmcp environment ${environment}

## AWS Region
-erlmcp aws_region ${aws_region}

## Instance ID (populated at boot)
-erlmcp instance_id ${instance_id}

## -----------------------------------------------------------------------------
## Additional Flags (Environment-Specific)
## -----------------------------------------------------------------------------

${extra_vm_args}
