# erlmcp environment - generated by SessionStart.sh
# Source this file to get OTP 28+ environment in other hooks
export ERLMCP_OTP_BIN_PATH="/Users/sac/erlmcp/.erlmcp/otp-28.3.1/bin"
export ERLMCP_OTP_VERSION="28.3.1"
export ERLMCP_OTP_BIN="/Users/sac/erlmcp/.erlmcp/otp-28.3.1/bin/erl"
export ERLMCP_CACHE="/Users/sac/erlmcp/.erlmcp/cache/"
# System bins FIRST to preserve standard commands
export PATH="/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:${ERLMCP_OTP_BIN_PATH}:$PATH"
export CLAUDE_CODE_REMOTE=true
export ERLMCP_PROFILE=cloud
export TERM=dumb
export REBAR_COLOR=none
export ERL_AFLAGS="-kernel shell_history enabled"
