#!/usr/bin/env bash
# CLAUDE.md Rules Synchronization Utility
# Synchronizes quality rules from CLAUDE.md to enforcement points:
# - Pre-commit hooks
# - CI/CD workflows
# - Quality gate scripts
# Ensures consistency across all validation mechanisms

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLAUDE_MD="$PROJECT_ROOT/CLAUDE.md"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

log_sync() {
    echo -e "${BLUE}[SYNC]${NC} $*"
}

# Sync to git pre-commit hook
sync_git_hooks() {
    log_sync "Synchronizing to git pre-commit hooks..."

    local git_hook_dir="$PROJECT_ROOT/.git/hooks"
    local pre_commit="$git_hook_dir/pre-commit"
    local hook_source="$PROJECT_ROOT/.claude/hooks/pre-commit-validate.sh"

    if [[ ! -d "$git_hook_dir" ]]; then
        log_warn "Not a git repository, skipping git hooks sync"
        return 0
    fi

    if [[ ! -f "$hook_source" ]]; then
        log_error "Hook source not found: $hook_source"
        return 1
    fi

    # Create pre-commit hook that calls our validation script
    cat > "$pre_commit" << 'EOF'
#!/usr/bin/env bash
# Git pre-commit hook - Generated by claude-md-sync.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VALIDATOR="$PROJECT_ROOT/.claude/hooks/pre-commit-validate.sh"

if [[ -f "$VALIDATOR" ]]; then
    exec "$VALIDATOR"
else
    echo "ERROR: Pre-commit validator not found at $VALIDATOR"
    exit 1
fi
EOF

    chmod +x "$pre_commit"
    chmod +x "$hook_source"

    log_info "✅ Git pre-commit hook installed at $pre_commit"
}

# Sync to CI/CD workflows
sync_ci_workflows() {
    log_sync "Synchronizing to CI/CD workflows..."

    local ci_dir="$PROJECT_ROOT/.github/workflows"

    if [[ ! -d "$ci_dir" ]]; then
        log_warn "CI workflow directory not found, skipping CI sync"
        return 0
    fi

    # Update CI workflows to include CLAUDE.md validation
    for workflow in "$ci_dir"/*.yml; do
        if [[ -f "$workflow" ]]; then
            if grep -q "claude-md-enforcer" "$workflow"; then
                log_info "✅ Workflow already includes enforcer: $(basename "$workflow")"
            else
                log_warn "Workflow missing enforcer: $(basename "$workflow")"
                log_warn "Add this step to your workflow:"
                echo ""
                echo "      - name: Validate CLAUDE.md rules"
                echo "        run: |"
                echo "          chmod +x tools/claude-md-enforcer.sh"
                echo "          ./tools/claude-md-enforcer.sh"
                echo ""
            fi
        fi
    done
}

# Sync to Makefile
sync_makefile() {
    log_sync "Synchronizing to Makefile..."

    local makefile="$PROJECT_ROOT/Makefile"

    if [[ ! -f "$makefile" ]]; then
        log_warn "Makefile not found, skipping Makefile sync"
        return 0
    fi

    if grep -q "claude-md-enforcer" "$makefile"; then
        log_info "✅ Makefile already includes enforcer target"
    else
        log_warn "Makefile missing enforcer target"
        log_warn "Add this target to your Makefile:"
        echo ""
        echo "validate-claude-md:"
        echo "	@chmod +x tools/claude-md-enforcer.sh"
        echo "	@./tools/claude-md-enforcer.sh"
        echo ""
        echo "check: compile xref dialyzer test validate-claude-md"
        echo ""
    fi
}

# Sync to rebar.config
sync_rebar_config() {
    log_sync "Checking rebar.config for hooks..."

    local rebar_config="$PROJECT_ROOT/rebar.config"

    if [[ ! -f "$rebar_config" ]]; then
        log_warn "rebar.config not found, skipping rebar sync"
        return 0
    fi

    if grep -q "provider_hooks" "$rebar_config"; then
        log_info "✅ rebar.config has provider hooks configured"
    else
        log_info "rebar.config checked (no automatic hooks needed)"
    fi
}

# Verify all enforcement points
verify_enforcement() {
    log_sync "Verifying enforcement points..."

    local enforcer="$PROJECT_ROOT/tools/claude-md-enforcer.sh"
    local post_task_hook="$PROJECT_ROOT/.claude/hooks/post-task-validate.sh"
    local pre_commit_hook="$PROJECT_ROOT/.claude/hooks/pre-commit-validate.sh"
    local git_hook="$PROJECT_ROOT/.git/hooks/pre-commit"

    # Check enforcer
    if [[ -f "$enforcer" ]]; then
        log_info "✅ CLAUDE.md enforcer exists"
        chmod +x "$enforcer"
    else
        log_error "❌ CLAUDE.md enforcer missing"
    fi

    # Check post-task hook
    if [[ -f "$post_task_hook" ]]; then
        log_info "✅ Post-task hook exists"
        chmod +x "$post_task_hook"
    else
        log_error "❌ Post-task hook missing"
    fi

    # Check pre-commit hook
    if [[ -f "$pre_commit_hook" ]]; then
        log_info "✅ Pre-commit hook script exists"
        chmod +x "$pre_commit_hook"
    else
        log_error "❌ Pre-commit hook script missing"
    fi

    # Check git hook
    if [[ -f "$git_hook" ]]; then
        log_info "✅ Git pre-commit hook installed"
    else
        log_warn "⚠️  Git pre-commit hook not installed"
    fi
}

# Main sync
main() {
    log_sync "CLAUDE.md Rules Synchronization"
    log_sync "Project: erlmcp"
    log_sync "Root: $PROJECT_ROOT"
    echo ""

    # Verify CLAUDE.md exists
    if [[ ! -f "$CLAUDE_MD" ]]; then
        log_error "CLAUDE.md not found at $CLAUDE_MD"
        exit 1
    fi

    log_info "CLAUDE.md found at $CLAUDE_MD"
    echo ""

    # Sync to all enforcement points
    sync_git_hooks
    echo ""

    sync_ci_workflows
    echo ""

    sync_makefile
    echo ""

    sync_rebar_config
    echo ""

    verify_enforcement
    echo ""

    log_sync "✅ Synchronization complete"
    log_sync "Enforcement points updated and verified"
}

main "$@"
