apiVersion: v1
kind: Service
metadata:
  name: erlmcp-canary
  namespace: erlmcp-prod
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: erlmcp
